(() => {
'use strict';
const metrics=[['weight','Peso','kg'],['bmi','IMC','kg/m2'],['waist','Cintura','cm'],['glutes','Glúteos','cm'],['hips','Cadera','cm'],['chest','Pecho','cm'],['abdomen','Abdomen','cm'],['shoulders','Hombros','cm'],['leftArm','Bíceps / brazo izq.','cm'],['rightArm','Bíceps / brazo der.','cm'],['leftThigh','Muslo izq.','cm'],['rightThigh','Muslo der.','cm'],['leftCalf','Pantorrilla izq.','cm'],['rightCalf','Pantorrilla der.','cm']];
const n=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
const b=(text,fn)=>{const e=n('button',text);e.type='button';e.onclick=fn;return e;};
const fmt=(x,d=1)=>Number.isFinite(Number(x))?Number(x).toFixed(d).replace(/\.0$/,''):'—';
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const def=k=>metrics.find(x=>x[0]===k)||[k,k,'cm'];
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
function age(student){if(!student?.birth_date)return null;const d=new Date(student.birth_date+'T12:00:00'),now=new Date();let a=now.getFullYear()-d.getFullYear();if(now<new Date(now.getFullYear(),d.getMonth(),d.getDate()))a--;return a;}
function currentValue(metric,student,rows){const last=rows.at(-1);if(metric==='weight')return Number(last?.weight_kg)||null;if(metric==='bmi'){const h=Number(student?.height_cm),w=Number(last?.weight_kg);return h>0&&w>0?w/((h/100)**2):null;}return Number(last?.values_cm?.[metric])||null;}
function goalText(student){return norm((student?.goals||[]).join(' '));}
function suggest(student,rows){const out=[],years=age(student),last=rows.at(-1),w=Number(last?.weight_kg),h=Number(student?.height_cm),waist=Number(last?.values_cm?.waist),text=goalText(student);if(years!==null&&years<18)return [{kind:'context',title:'Referencias adultas desactivadas',body:'Por la edad registrada, Dulus no propone metas automáticas de peso o IMC para este perfil. El seguimiento puede continuar con objetivos definidos por un profesional.'}];if(!(w>0)||!(h>0))return out;const bmi=w/((h/100)**2),ratio=waist>0?waist/h:null;
 if(/perder|grasa|adelgazar|definir|peso/.test(text)&&bmi>=25){if(ratio!==null&&ratio<.5)out.push({kind:'context',title:'No fijar pérdida de peso automática todavía',body:'El IMC es alto, pero cintura/estatura está por debajo de 0.50. Revisa masa muscular y objetivo antes de elegir un peso.'});else{const target=Number((w*.95).toFixed(1)),targetBmi=target/((h/100)**2);out.push({kind:'goal',metric:'weight',target,date:null,title:'Primer hito sugerido',body:'5% menos que el peso actual como primer hito, no como peso final. Equivale aproximadamente a IMC '+fmt(targetBmi,1)+'. La fecha objetivo queda a elección del alumno o coach.'});}}
 if(/gluteo/.test(text)&&currentValue('glutes',student,rows)!=null)out.push({kind:'context',title:'Glúteos: meta manual recomendada',body:'No existe un tamaño ideal universal. Fija una meta propia o espera varias mediciones para usar la tendencia real.'});
 if(/bicep|brazo/.test(text)&&(currentValue('leftArm',student,rows)!=null||currentValue('rightArm',student,rows)!=null))out.push({kind:'context',title:'Bíceps / brazo: meta manual recomendada',body:'Dulus no adivina un tamaño máximo. El coach puede fijar un siguiente hito según estructura, entrenamiento y tendencia.'});return out;}
function goalCard(goal,student,rows,api,rerender){const card=n('article',undefined,'body-goal-card'),[,,unit]=def(goal.metric),current=currentValue(goal.metric,student,rows),start=Number(goal.start_value),target=Number(goal.target_value),title=n('div',undefined,'body-goal-title');title.append(n('strong',def(goal.metric)[1]),n('span',goal.created_by===student.user_id?'Definida por alumno':'Definida por coach'));card.append(title);
 const values=n('div',undefined,'body-goal-values');for(const [v,l] of [[start?fmt(start)+' '+unit:'—','Inicio'],[current?fmt(current)+' '+unit:'—','Actual'],[fmt(target)+' '+unit,'Objetivo']]){const x=n('div');x.append(n('strong',v),n('small',l));values.append(x);}card.append(values);
 if(start&&current&&target!==start){const raw=(current-start)/(target-start)*100,progress=clamp(raw,0,100),bar=n('div',undefined,'body-goal-progress'),fill=n('span');fill.style.width=progress+'%';bar.append(fill);card.append(bar,n('small',fmt(raw,0)+'% del trayecto medido'));if((target>start&&current>=target)||(target<start&&current<=target))card.append(n('p','Meta alcanzada según la última medición ✓','body-goal-reached'));}
 if(goal.target_date)card.append(n('small','Fecha objetivo: '+goal.target_date));if(goal.note)card.append(n('p',goal.note));const actions=n('div',undefined,'body-goal-actions'),close=b('Cerrar meta',()=>{}),remove=b('Eliminar meta',()=>{});let armed=false,timer=null;close.onclick=async()=>{if(!armed){armed=true;close.textContent='Confirmar cierre';clearTimeout(timer);timer=setTimeout(()=>{armed=false;close.textContent='Cerrar meta';},4000);return;}close.disabled=true;try{await api.check(api.db.rpc('dulus_close_body_goal',{p_goal:goal.id}));await rerender();}catch{close.disabled=false;close.textContent='Reintentar';}};let removeArmed=false,removeTimer=null;remove.onclick=async()=>{if(!removeArmed){removeArmed=true;remove.textContent='Confirmar eliminación';clearTimeout(removeTimer);removeTimer=setTimeout(()=>{removeArmed=false;remove.textContent='Eliminar meta';},4000);return;}remove.disabled=true;try{await api.check(api.db.rpc('dulus_delete_body_goal',{p_goal:goal.id}));await rerender();}catch{remove.disabled=false;remove.textContent='Reintentar';}};actions.append(close,remove);card.append(actions);return card;}
function profileEditor(student,api,rerender){const box=n('div',undefined,'body-profile-editor'),sexLabel=n('label','Referencia corporal'),sex=n('select');for(const [v,t] of [['','No indicar'],['male','Hombre'],['female','Mujer'],['unspecified','Prefiero no indicar']]){const o=new Option(t,v);sex.append(o);}sex.value=student.body_reference||'';const birthLabel=n('label','Fecha de nacimiento (opcional)'),birth=n('input');birth.type='date';birth.max=new Date().toISOString().slice(0,10);birth.value=student.birth_date||'';const save=b('Guardar perfil corporal',()=>{}),status=n('small','La fecha de nacimiento es opcional. Si la añades, Dulus usa la edad para validar referencias; si no, el seguimiento continúa. El IMC adulto no cambia por sexo.');sexLabel.append(sex);birthLabel.append(birth);save.onclick=async()=>{save.disabled=true;status.textContent='Guardando…';try{const payload={body_reference:sex.value||null,birth_date:birth.value||null};await api.check(api.db.from('dulus_students').update(payload).eq('id',student.id).select('id,body_reference,birth_date').single());Object.assign(student,payload);status.textContent='Perfil corporal guardado ✓';document.dispatchEvent(new CustomEvent('dulus:body-profile-changed',{detail:{studentId:student.id}}));await rerender();}catch(e){status.textContent=e.message||'No se pudo guardar.';save.disabled=false;}};box.append(sexLabel,birthLabel,save,status);return box;}
function goalEditor(student,rows,api,rerender){const form=n('form',undefined,'body-goal-form'),metricLabel=n('label','Medida objetivo'),metric=n('select');for(const [k,l] of metrics)metric.append(new Option(l,k));const targetLabel=n('label','Objetivo'),target=n('input');target.type='number';target.step='.1';target.min='.1';target.max='999';target.required=true;const dateLabel=n('label','Fecha objetivo (opcional)'),date=n('input');date.type='date';date.min=new Date().toISOString().slice(0,10);const noteLabel=n('label','Nota (opcional)'),note=n('input');note.type='text';note.maxLength=500;const current=n('small'),save=n('button','Guardar meta');save.type='submit';metricLabel.append(metric);targetLabel.append(target);dateLabel.append(date);noteLabel.append(note);const refresh=()=>{const [,,unit]=def(metric.value),v=currentValue(metric.value,student,rows);target.step=metric.value==='bmi'?'.1':'.1';current.textContent='Actual: '+(v?fmt(v)+' '+unit:'sin dato registrado')+'. Esta meta es opcional.';};metric.onchange=refresh;refresh();form.append(metricLabel,targetLabel,dateLabel,noteLabel,current,save);
 form.onsubmit=async e=>{e.preventDefault();const [,,unit]=def(metric.value),start=currentValue(metric.value,student,rows),value=Number(target.value);if(!(value>0))return;save.disabled=true;try{await api.check(api.db.rpc('dulus_save_body_goal',{p_student:student.id,p_metric:metric.value,p_start:start,p_target:value,p_unit:unit,p_date:date.value||null,p_note:note.value.trim()}));await rerender();}catch(err){current.textContent=err.message||'No se pudo guardar la meta.';save.disabled=false;}};return form;}
function goalState(goal,student,rows){const current=currentValue(goal.metric,student,rows),start=Number(goal.start_value)||null,target=Number(goal.target_value),[,,unit]=def(goal.metric),raw=start&&current&&target!==start?(current-start)/(target-start)*100:null,reached=current!==null&&((target>(start??current)&&current>=target)||(target<(start??current)&&current<=target));return {goal,current,start,target,unit,raw,reached,label:def(goal.metric)[1]};}
function dashboardSummary({student,goals,measurements}){const own=goals.filter(g=>g.student_id===student.id&&g.active).map(g=>goalState(g,student,measurements.filter(r=>r.student_id===student.id).sort((a,b)=>String(a.measured_on).localeCompare(String(b.measured_on)))));if(!own.length)return null;const box=n('section',undefined,'body-goal-dashboard');box.append(n('h3','Mis metas corporales'));for(const state of own.slice(0,3)){const card=n('article'),line=state.current===null?'Actual sin dato':fmt(state.current)+' '+state.unit+' → '+fmt(state.target)+' '+state.unit;card.append(n('strong',state.label),n('p',line));if(state.raw!==null)card.append(n('small',fmt(state.raw,0)+'% del trayecto'+(state.reached?' · Meta alcanzada ✓':'')));else card.append(n('small','Registra una medición para calcular progreso.'));box.append(card);}return box;}
window.DulusBodyGoals={age,suggest,currentValue,goalState,dashboardSummary,create(api){const host=document.getElementById('student-body-goals');let current=null,token=0;async function load(student){const [rows,goals]=await Promise.all([api.check(api.db.from('dulus_measurements').select('*').eq('student_id',student.id).order('measured_on')),api.check(api.db.from('dulus_body_goals').select('*').eq('student_id',student.id).eq('active',true).order('created_at'))]);return {rows,goals};}
 async function render(student){const id=++token;current=student;host.replaceChildren();const section=n('details',undefined,'body-goals-section');section.append(n('summary','Objetivos corporales avanzados · opcional'));const intro=n('p','Fija metas numéricas solo cuando aporten al seguimiento. Dulus separa referencia, meta elegida y progreso real; no promete un resultado físico máximo.','progress-note');section.append(intro);host.append(section);let data;try{data=await load(student);}catch{if(id===token)section.append(n('p','No se pudieron cargar las metas corporales.'));return;}if(id!==token||current?.id!==student.id)return;
 const rerender=()=>render(student);section.append(profileEditor(student,api,rerender));const years=age(student);if(years!==null)section.append(n('p','Edad calculada: '+years+' años · se usa solo en referencias donde la edad realmente cambia la interpretación.','progress-note'));if(years!==null&&years<18)section.append(n('p','Las referencias adultas de IMC no se aplicarán a este perfil porque es menor de 18 años.','body-goal-warning'));else if(years===null)section.append(n('p','Fecha de nacimiento opcional: si la añades, Dulus podrá validar la edad y afinar referencias. Si no, las metas y medidas siguen funcionando.','progress-note'));
 const suggestions=suggest(student,data.rows);if(suggestions.length){const suggestBox=n('div',undefined,'body-goal-suggestions');suggestBox.append(n('h4','Sugerencias de Dulus'));for(const s of suggestions){const card=n('article');card.append(n('strong',s.title),n('p',s.body));if(s.kind==='goal'){const use=b('Usar como primer hito',async()=>{use.disabled=true;const start=currentValue(s.metric,student,data.rows),unit=def(s.metric)[2];try{await api.check(api.db.rpc('dulus_save_body_goal',{p_student:student.id,p_metric:s.metric,p_start:start,p_target:s.target,p_unit:unit,p_date:null,p_note:'Primer hito sugerido por Dulus; revisable por coach y alumno. Fecha objetivo opcional.'}));await rerender();}catch{use.disabled=false;use.textContent='Reintentar';}});card.append(use);}suggestBox.append(card);}section.append(suggestBox);}
 const active=n('div',undefined,'body-goal-list');active.append(n('h4','Metas activas'));if(!data.goals.length)active.append(n('p','No hay metas corporales activas. No es obligatorio crear una.'));for(const g of data.goals)active.append(goalCard(g,student,data.rows,api,rerender));section.append(active);const create=n('details',undefined,'body-goal-create');create.append(n('summary','Añadir una meta'));create.append(goalEditor(student,data.rows,api,rerender));section.append(create);}
 document.addEventListener('dulus:measurements-changed',e=>{if(current&&e.detail?.studentId===current.id)render(current);});return {render,clear(){token++;current=null;host?.replaceChildren();}};}};
})();
