(() => {
'use strict';
const n=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
const button=(text,fn)=>{const e=n('button',text);e.type='button';e.onclick=fn;return e;};
const todayKey=()=>{const d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');};
function age(since){if(!since)return null;const raw=String(since),date=raw.length===10?raw:raw.slice(0,10);const ms=new Date(todayKey()+'T12:00:00')-new Date(date+'T12:00:00');if(!Number.isFinite(ms))return null;return Math.max(0,Math.floor(ms/86400000));}
function ageText(since){const d=age(since);if(d===null)return 'Detectado en la revisión actual';if(d===0)return 'Desde hoy';if(d===1)return 'Pendiente desde hace 1 día';return 'Pendiente desde hace '+d+' días';}
function lane(signal){const t=signal.title;if(signal.severity>=2||/Dolor alto|Molestia a revisar|Inactividad|Video pendiente|Comentario pendiente|Rendimiento bajando/.test(t))return 'today';return 'week';}
function build(args){if(!window.DulusCoachAction||!window.DulusProgress)return {today:[],week:[],rows:[]};const progressData=window.DulusProgress.build(args.api,args.sessions,args.plans,args.roster),rows=args.roster.map(student=>window.DulusCoachAction.analyzeStudent({...args,student,progressData}));const tasks=[];
 for(const row of rows){if(!row.signals.length)continue;const ordered=[...row.signals].sort((a,b)=>b.severity-a.severity||(age(b.since)??-1)-(age(a.since)??-1)),top=ordered[0];tasks.push({student:row.student,row,signal:top,extra:ordered.length-1,lane:lane(top),age:age(top.since)});}
 tasks.sort((a,b)=>(a.lane===b.lane?0:a.lane==='today'?-1:1)||b.signal.severity-a.signal.severity||(b.age??-1)-(a.age??-1)||a.student.name.localeCompare(b.student.name,'es'));
 return {today:tasks.filter(x=>x.lane==='today'),week:tasks.filter(x=>x.lane==='week'),rows,tasks};}
function render(args){if(!args.api.coach?.())return null;const model=build(args),section=n('section',undefined,'coach-agenda');section.append(n('p','AGENDA INTELIGENTE','eyebrow'),n('h3','Qué necesita tu atención'));const stats=n('div',undefined,'coach-agenda-stats');for(const [v,l] of [[model.today.length,'Hoy'],[model.week.length,'Esta semana'],[model.tasks.length,'Alumnos con acción']]){const c=n('div');c.append(n('strong',String(v)),n('span',l));stats.append(c);}section.append(stats);
 if(!model.tasks.length){section.append(n('p','No hay alumnos que requieran una acción concreta ahora. El resto puede seguir con su plan.','coach-agenda-clear'));return section;}
 const renderGroup=(title,items)=>{if(!items.length)return;const group=n('div',undefined,'coach-agenda-group');group.append(n('h4',title));for(const task of items){const card=n('article',undefined,'coach-agenda-card');card.dataset.level=String(task.signal.severity);card.dataset.studentId=task.student.id;const head=n('div',undefined,'coach-agenda-card-head');head.append(n('strong',task.student.name),n('span',task.signal.title));card.append(head,n('p',task.signal.evidence),n('small',ageText(task.signal.since)+(task.extra?' · +'+task.extra+' asunto'+(task.extra===1?'':'s')+' más':'')),n('small','Siguiente paso: '+task.signal.action,'coach-agenda-next'));
 const actions=n('div',undefined,'coach-agenda-actions'),open=button('Abrir alumno',()=>{args.api.select?.(task.student.id);document.getElementById('student-panel')?.scrollIntoView({behavior:'smooth',block:'start'});}),detail=button('Ver detalle',()=>{const target=document.querySelector('.coach-action-card[data-student-id="'+task.student.id+'"]');target?.scrollIntoView({behavior:'smooth',block:'center'});});actions.append(open,detail);if(/Video pendiente|Comentario pendiente/.test(task.signal.title)){actions.append(button('Ir a avisos',()=>document.querySelector('.coach-inbox')?.scrollIntoView({behavior:'smooth',block:'start'})));}card.append(actions);group.append(card);}section.append(group);};
 renderGroup('Hoy',model.today);renderGroup('Esta semana',model.week);return section;}
window.DulusCoachAgenda={build,render};
})();