(() => {
'use strict';
const n=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
const avg=a=>a.length?a.reduce((s,x)=>s+x,0)/a.length:null;
const round=(x,d=1)=>Number.isFinite(Number(x))?Number(Number(x).toFixed(d)):null;
const key=d=>d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');
const shift=(date,days)=>{const d=new Date(date+'T12:00:00');d.setDate(d.getDate()+days);return key(d);};
const between=(date,start,end)=>date>=start&&date<=end;
const metricValue=(row,k)=>k==='weight'?Number(row.weight_kg):Number(row.values_cm?.[k]);
function bounds(days=28){const today=key(new Date()),start=shift(today,-days+1),prevEnd=shift(start,-1),prevStart=shift(prevEnd,-days+1);return {today,start,prevStart,prevEnd,days};}
function adherence(student,plans,sessions,start,end){const own=plans.filter(p=>p.student_id===student.id);let due=0,done=0;for(let d=start;d<=end;d=shift(d,1)){const day=new Date(d+'T12:00:00').getDay();for(const p of own){if(p.start_date>d||(p.end_date&&p.end_date<d)||!p.days?.includes(day))continue;due++;const s=sessions.find(x=>x.plan_id===p.id&&x.date===d);if(s&&(s.completed_ids?.length||0)>=(s.total_exercises||Infinity))done++;}}return {due,done,rate:due?done/due:null};}
function lastIn(rows,start,end,getDate){return rows.filter(x=>between(getDate(x),start,end)).sort((a,b)=>String(getDate(a)).localeCompare(String(getDate(b)))).at(-1)||null;}
function confidence({sessions,strengthPoints,measurePoints,performancePoints}){const score=(sessions>=8?2:sessions>=4?1:0)+(strengthPoints>=8?2:strengthPoints>=4?1:0)+(measurePoints>=2?1:0)+(performancePoints>=1?1:0);return score>=4?'Alta':score>=2?'Media':'Inicial';}
function strengthReview(api,student,sessions,plans,roster,b){const data=window.DulusProgress?.build?.(api,sessions,plans,roster);if(!data)return {items:[],points:0};const items=[];let points=0;for(const s of data.exerciseSeries.values()){if(s.studentId!==student.id)continue;const prev=lastIn(s.points,b.prevStart,b.prevEnd,x=>x.date),cur=lastIn(s.points,b.start,b.today,x=>x.date);points+=s.points.filter(x=>between(x.date,b.start,b.today)).length;if(!prev||!cur)continue;const delta=(cur.e1rm/prev.e1rm-1)*100;items.push({exercise:s.name,muscle:s.muscle,prev:prev.e1rm,current:cur.e1rm,delta});}
 const byMuscle=new Map();for(const x of items){const a=byMuscle.get(x.muscle)||[];a.push(x.delta);byMuscle.set(x.muscle,a);}return {items:[...byMuscle].map(([muscle,v])=>({muscle,delta:avg(v),count:v.length})).sort((a,b)=>b.delta-a.delta),points};}
function measureReview(student,rows,b){const profile=window.DulusGoalTracking?.profile?.(student),keys=(profile?.body||[]).map(x=>x.key);const items=[];let points=0;for(const k of keys){const current=lastIn(rows,b.start,b.today,x=>x.measured_on),previous=lastIn(rows,b.prevStart,b.prevEnd,x=>x.measured_on),cur=current?metricValue(current,k):NaN,prev=previous?metricValue(previous,k):NaN;if(Number.isFinite(cur))points++;if(Number.isFinite(cur)&&Number.isFinite(prev)){items.push({key:k,label:(window.DulusGoalTracking?.bodyDefs?.[k]?.[0]||k),prev,current:cur,delta:cur-prev});}}return {items,points};}
function performanceReview(student,entries,b){const profile=window.DulusGoalTracking?.profile?.(student),keys=(profile?.performance||[]).map(x=>x.key),items=[];let points=0;for(const k of keys){const own=entries.filter(x=>x.student_id===student.id&&x.metric===k);const cur=lastIn(own,b.start,b.today,x=>x.measured_on),prev=lastIn(own,b.prevStart,b.prevEnd,x=>x.measured_on);if(cur)points++;if(cur&&prev){const lower=/sprint/.test(k),delta=Number(cur.value)-Number(prev.value);items.push({key:k,label:window.DulusGoalTracking?.perfDefs?.[k]?.[0]||k,prev:Number(prev.value),current:Number(cur.value),delta,improved:lower?delta<0:delta>0,unit:cur.unit});}}return {items,points};}
function recoveryReview(student,plans,sessions,b){const ids=new Set(plans.filter(p=>p.student_id===student.id).map(p=>p.id)),own=sessions.filter(s=>ids.has(s.plan_id));const slice=(start,end)=>own.filter(s=>between(s.date,start,end)),stats=rows=>({fat:avg(rows.map(s=>Number(s.details?.fatigue)).filter(Number.isFinite)),pain:rows.reduce((m,s)=>Math.max(m,Number(s.details?.pain||0)),0),count:rows.length});return {current:stats(slice(b.start,b.today)),previous:stats(slice(b.prevStart,b.prevEnd))};}
function build({api,student,plans,sessions,measurements=[],bodyGoals=[],performanceEntries=[],decisions=[],roster}){const b=bounds(),adNow=adherence(student,plans,sessions,b.start,b.today),adPrev=adherence(student,plans,sessions,b.prevStart,b.prevEnd),strength=strengthReview(api,student,sessions,plans,roster,b),rows=measurements.filter(x=>x.student_id===student.id),measures=measureReview(student,rows,b),performance=performanceReview(student,performanceEntries,b),recovery=recoveryReview(student,plans,sessions,b),goal=bodyGoals.find(g=>g.student_id===student.id&&g.active),ownPlans=new Set(plans.filter(p=>p.student_id===student.id).map(p=>p.id)),ownSessions=sessions.filter(s=>ownPlans.has(s.plan_id));
 const goalText=String((student.goals||[]).join(' ')).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase(),fatLoss=/perder|grasa|adelgazar|definir|cintura/.test(goalText),gluteGoal=/gluteo|glute/.test(goalText),armGoal=/bicep|brazo|arm/.test(goalText);
 const evidenceDates=[...ownSessions.map(x=>x.date),...rows.map(x=>x.measured_on),...performanceEntries.filter(x=>x.student_id===student.id).map(x=>x.measured_on)].sort(),historyDays=evidenceDates.length?Math.max(0,Math.floor((new Date(b.today+'T12:00:00')-new Date(evidenceDates[0]+'T12:00:00'))/86400000)):0,ready=historyDays>=28;
 const wins=[],watch=[],stable=[];if(adNow.rate!==null){const pct=Math.round(adNow.rate*100),change=adPrev.rate===null?null:(adNow.rate-adPrev.rate)*100;if(pct>=80&&(!Number.isFinite(change)||change>=-10))wins.push('Constancia '+pct+'% en las últimas 4 semanas.');else if(pct<60)watch.push('Constancia baja: '+pct+'% en las últimas 4 semanas.');else stable.push('Constancia '+pct+'% · margen para mejorar.');}
 for(const x of strength.items){if(x.delta>2)wins.push(x.muscle+' mejoró '+round(x.delta,1)+'% en e1RM comparable.');else if(x.delta<-2)watch.push(x.muscle+' bajó '+Math.abs(round(x.delta,1))+'% en e1RM comparable.');else stable.push(x.muscle+' se mantuvo estable.');}
 for(const x of performance.items){const amount=Math.abs(round(x.delta,1));if(x.improved)wins.push(x.label+' mejoró '+amount+' '+x.unit+'.');else if(amount>0)watch.push(x.label+' retrocedió '+amount+' '+x.unit+'.');}
 for(const x of measures.items){const active=goal?.metric===x.key;if(active){const target=Number(goal.target_value),better=Math.abs(x.current-target)<Math.abs(x.prev-target);(better?wins:watch).push(x.label+' '+(better?'se acercó':'se alejó')+' de la meta · '+round(x.prev,1)+' → '+round(x.current,1)+' '+(x.key==='weight'?'kg':'cm')+'.');}else if(fatLoss&&x.key==='waist'&&Math.abs(x.delta)>=0.5){(x.delta<0?wins:watch).push('Cintura '+(x.delta<0?'bajó ':'subió ')+Math.abs(round(x.delta,1))+' cm · señal compatible con el objetivo de composición corporal.');}else if(gluteGoal&&x.key==='glutes'&&Math.abs(x.delta)>=0.8){(x.delta>0?wins:watch).push('Glúteos '+(x.delta>0?'aumentó ':'disminuyó ')+Math.abs(round(x.delta,1))+' cm · interprétalo junto con fuerza y técnica de medición.');}else if(armGoal&&/Arm$/.test(x.key)&&Math.abs(x.delta)>=0.8){(x.delta>0?wins:watch).push(x.label+' '+(x.delta>0?'aumentó ':'disminuyó ')+Math.abs(round(x.delta,1))+' cm · interprétalo junto con fuerza y consistencia de medición.');}else stable.push(x.label+' cambió '+(x.delta>=0?'+':'')+round(x.delta,1)+' '+(x.key==='weight'?'kg':'cm')+'; se muestra como contexto, no como bueno/malo.');}
 const rf=recovery.current.fat,rp=recovery.previous.fat;if(recovery.current.pain>=4)watch.unshift('Dolor reciente hasta '+recovery.current.pain+'/10: recuperación primero.');else if(rf!==null&&rf>=8)watch.push('Fatiga alta: '+round(rf,1)+'/10 de media.');else if(rf!==null&&rp!==null&&rf<=rp-1)wins.push('Fatiga media bajó de '+round(rp,1)+' a '+round(rf,1)+'/10.');
 const latestDecision=decisions.filter(x=>x.student_id===student.id).sort((a,b)=>String(b.effective_on).localeCompare(String(a.effective_on))||String(b.created_at).localeCompare(String(a.created_at)))[0]||null,decisionImpact=latestDecision&&window.DulusCoachDecisions?.impact?.(latestDecision,{student,api,plans,sessions});const conf=confidence({sessions:recovery.current.count,strengthPoints:strength.points,measurePoints:measures.points,performancePoints:performance.points});let focus;if(recovery.current.pain>=4)focus=watch[0]||'Priorizar recuperación.';else if(decisionImpact&&decisionImpact.days<14)focus='Observar el ajuste reciente: han pasado '+decisionImpact.days+' días. Evita volver a cambiar el plan salvo una señal clara de seguridad o recuperación.';else if(!ready)focus='Completar el primer ciclo de datos antes de hacer cambios importantes; las señales actuales son provisionales.';else focus=watch[0]||(wins.length?'Mantener lo que funciona y seguir el próximo dato programado.':'Mantener el plan y recopilar un ciclo más antes de cambiarlo.');return {student,bounds:b,ready,historyDays,confidence:conf,wins,watch,stable,focus,adherence:{current:adNow,previous:adPrev},strength,measures,performance,recovery,latestDecision,decisionImpact};}
function render({api,roster,plans,sessions,measurements=[],bodyGoals=[],performanceEntries=[],decisions=[]}){if(!roster.length)return null;const section=n('details',undefined,'cycle-review');section.open=!api.coach();section.append(n('summary','Revisión automática · ciclo de 4 semanas'));const head=n('div',undefined,'cycle-review-head'),select=n('select');let student=api.student?.()||roster[0];if(!roster.some(x=>x.id===student?.id))student=roster[0];if(api.coach()){const label=n('label','Alumno');for(const r of roster)select.append(new Option(r.name,r.id));select.value=student.id;label.append(select);head.append(label);}const body=n('div');section.append(head,body);
 function draw(){if(api.coach())student=roster.find(x=>x.id===select.value)||roster[0];const model=build({api,student,plans,sessions,measurements,bodyGoals,performanceEntries,decisions,roster});body.replaceChildren();body.append(n('p',model.bounds.start+' → '+model.bounds.today+' · comparado con '+model.bounds.prevStart+' → '+model.bounds.prevEnd,'progress-note'));const top=n('div',undefined,'cycle-review-top');for(const [v,l] of [[model.ready?'Ciclo evaluable':'En construcción','Estado'],[model.confidence,'Confianza'],[model.adherence.current.rate===null?'—':Math.round(model.adherence.current.rate*100)+'%','Constancia 4 sem']]){const c=n('div');c.append(n('strong',String(v)),n('small',l));top.append(c);}body.append(top);
  if(!model.ready)body.append(n('p','Todavía no hay 4 semanas completas de historial. Dulus muestra señales provisionales, pero no recomienda cambiar el plan solo por ellas.','cycle-review-note'));
  const grid=n('div',undefined,'cycle-review-grid'),groups=[['Mejoró',model.wins,'good'],[model.ready?'Revisar':'Señales provisionales',model.watch,model.ready?'attention':'neutral'],['Contexto',model.stable,'neutral']];for(const [title,items,level] of groups){const card=n('article',undefined,'cycle-review-card');card.dataset.level=level;card.append(n('h4',title));if(items.length){for(const text of items.slice(0,4))card.append(n('p',text));if(items.length>4)card.append(n('small','+'+(items.length-4)+' señales más en las gráficas.'));}else card.append(n('p',title==='Revisar'?'Sin señales que exijan intervención ahora.':'Aún no hay datos suficientes en este bloque.'));grid.append(card);}body.append(grid);if(model.latestDecision){const d=model.latestDecision,impact=model.decisionImpact,ctx=n('article',undefined,'cycle-decision-context'),label=window.DulusCoachDecisions?.CATEGORIES?.[d.category]||'Ajuste';ctx.append(n('small','ÚLTIMO AJUSTE DEL COACH'),n('strong',label+' · '+d.summary),n('p','Motivo: '+d.reason),n('small',d.effective_on+' · '+(impact?.phase||'Sin evaluación')+' · confianza '+(impact?.confidence||'Inicial')));for(const note of impact?.notes?.slice(0,2)||[])ctx.append(n('p',note));body.append(ctx);}body.append(n('p','Próximo foco: '+model.focus,'cycle-review-focus'));
  const schedule=window.DulusTrackingSchedule?.build?.({student,measurements,performanceEntries});if(schedule?.next){const x=schedule.next;body.append(n('small','Próximo dato útil: '+x.label+' · '+x.text));}}
 select.onchange=draw;draw();return section;}
window.DulusCycleReview={build,render};
})();
