(() => {
'use strict';
const dayDiff=(a,b)=>Math.abs(Math.round((new Date(b+'T12:00:00')-new Date(a+'T12:00:00'))/86400000));
const bodyProtocols={
 weight:'Misma báscula y, si puedes, horario/condiciones parecidas. Mira la tendencia, no un solo día.',waist:'Cinta horizontal, abdomen relajado y mismo punto cada vez; mide tras una exhalación normal.',glutes:'Cinta horizontal en el punto de mayor perímetro y misma postura.',hips:'Usa siempre el mismo punto anatómico y mantén la cinta horizontal.',chest:'Mismo nivel del pecho, postura natural y respiración comparable.',abdomen:'Mismo punto del abdomen y misma respiración/posición.',leftArm:'Mismo punto del brazo y mismo estado cada vez (relajado o flexionado).',rightArm:'Mismo punto del brazo y mismo estado cada vez (relajado o flexionado).',leftThigh:'Mismo punto del muslo, misma postura y sin apretar la cinta.',rightThigh:'Mismo punto del muslo, misma postura y sin apretar la cinta.'
};
const perfProtocols={vertical_jump:'Mismo método de medición, superficie, calentamiento y tipo de salto.',broad_jump:'Mismo calentamiento, superficie y técnica de salida.',sprint_10m:'Misma distancia, superficie, salida y método de cronometraje.',sprint_20m:'Misma distancia, superficie, salida y método de cronometraje.',sprint_40m:'Misma distancia, superficie, salida y método de cronometraje.',pullups:'Mismo agarre, rango de movimiento y criterio de repetición.',plank:'Misma posición y mismo criterio para finalizar la prueba.'};
function bodyLimit(key){if(key==='weight')return {pct:4,minDays:3};if(/Arm|Forearm/.test(key))return {abs:3,minDays:10};if(/Thigh|Calf/.test(key))return {abs:4,minDays:10};return {abs:5,minDays:10};}
function bodyWarning(key,prev,current,days){if(!(prev>0)||!(current>0))return null;const lim=bodyLimit(key),delta=Math.abs(current-prev),pct=delta/prev*100;if(days<lim.minDays)return 'Se repitió muy pronto ('+days+' días). Puede servir, pero normalmente aporta más respetar el intervalo del plan.';if((lim.abs&&delta>=lim.abs)||(lim.pct&&pct>=lim.pct))return 'Cambio grande frente al último registro ('+(current-prev>=0?'+':'')+(current-prev).toFixed(1)+(key==='weight'?' kg':' cm')+'). Verifica técnica y punto de medición antes de guardarlo.';return null;}
function performanceWarning(metric,prev,current,days){if(!(prev>0)||!(current>0))return null;if(days<7)return 'La prueba se repitió muy pronto ('+days+' días). Repite solo si tenía sentido hacerlo y las condiciones fueron comparables.';const pct=Math.abs(current-prev)/prev*100,limit=/sprint/.test(metric)?10:metric==='vertical_jump'||metric==='broad_jump'?20:40;if(pct>=limit)return 'Cambio grande frente a la prueba anterior ('+pct.toFixed(1)+'%). Verifica método, superficie, calentamiento y criterio antes de confirmarlo.';return null;}
function latestBody(rows,key,beforeDate){return [...rows].filter(r=>r.measured_on<beforeDate).map(r=>({date:r.measured_on,value:key==='weight'?Number(r.weight_kg):Number(r.values_cm?.[key])})).filter(x=>Number.isFinite(x.value)&&x.value>0).sort((a,b)=>a.date.localeCompare(b.date)).at(-1)||null;}
function latestPerformance(entries,metric,beforeDate){return [...entries].filter(r=>r.metric===metric&&r.measured_on<beforeDate).map(r=>({date:r.measured_on,value:Number(r.value)})).filter(x=>Number.isFinite(x.value)&&x.value>0).sort((a,b)=>a.date.localeCompare(b.date)).at(-1)||null;}
function bodyWarnings(rows,date,weight,values){const out=[];if(weight>0){const prev=latestBody(rows,'weight',date);const w=prev&&bodyWarning('weight',prev.value,weight,dayDiff(prev.date,date));if(w)out.push('Peso: '+w);}for(const [key,value] of Object.entries(values||{})){const prev=latestBody(rows,key,date),w=prev&&bodyWarning(key,prev.value,Number(value),dayDiff(prev.date,date));if(w)out.push((window.DulusGoalTracking?.bodyDefs?.[key]?.[0]||key)+': '+w);}return out;}
function performanceWarnings(entries,metric,date,value){const prev=latestPerformance(entries,metric,date);if(!prev)return [];const w=performanceWarning(metric,prev.value,Number(value),dayDiff(prev.date,date));return w?[w]:[];}
window.DulusDataQuality={bodyProtocols,perfProtocols,bodyWarnings,performanceWarnings,latestBody,latestPerformance};
})();
