/* Catálogo extensible: cada entrada conserva el formato que usará el constructor de rutinas. */
const exercise = (id, name, muscleGroup, equipment, weighted, level, instructions, secondaryMuscles, alternatives = '', errors = [], tips = []) => ({
  id, name, alternativeName: alternatives, primaryMuscle: muscleGroup, secondaryMuscles,
  type: weighted ? 'Fuerza' : 'Peso corporal', equipment, weighted, level, instructions,
  commonErrors: errors.length ? errors : ['Perder el control del movimiento.', 'Usar un rango de movimiento incompleto.'],
  techniqueTips: tips.length ? tips : ['Mantén una cadencia controlada.', 'Prioriza la técnica antes de aumentar la carga.'],
  relatedVariants: [], media: { image: '', video: '', status: 'pending' },
  routineDefaults: { sets: null, reps: null, restSeconds: null }
});

const EXERCISE_EQUIPMENT = ['Todos', 'Peso corporal', 'Barra', 'Mancuernas', 'Máquina', 'Polea', 'Bandas', 'Kettlebell', 'Sin equipamiento'];
const EXERCISE_MUSCLES = ['Pecho', 'Espalda', 'Hombros', 'Bíceps', 'Tríceps', 'Antebrazos', 'Cuádriceps', 'Isquiotibiales', 'Glúteos', 'Pantorrillas', 'Core/Abdominales', 'Cuerpo completo'];

const EXERCISES = [
  exercise('press-banca-barra','Press de banca con barra','Pecho','Barra',true,'Intermedio',['Acuéstate con escápulas juntas y pies firmes.','Baja la barra hacia el pecho con control.','Empuja hasta extender los brazos sin despegar la espalda.'],['Tríceps','Hombros'], 'Press plano', ['Rebotar la barra sobre el pecho.','Abrir los codos en exceso.'], ['Mantén las muñecas sobre los codos.']),
  exercise('flexiones','Flexiones','Pecho','Peso corporal',false,'Principiante',['Forma una línea recta de cabeza a talones.','Desciende el pecho entre las manos.','Empuja el suelo para volver al inicio.'],['Tríceps','Core'], 'Push-ups', ['Dejar caer la cadera.','Acortar el recorrido.'], ['Aprieta glúteos y abdomen durante todo el movimiento.']),
  exercise('aperturas-mancuernas','Aperturas con mancuernas','Pecho','Mancuernas',true,'Intermedio',['Coloca las mancuernas sobre el pecho con codos suaves.','Abre en arco hasta sentir estiramiento.','Cierra el arco contrayendo el pecho.'],['Hombros'], 'Flyes', ['Bloquear los codos.','Bajar demasiado los brazos.'], ['Usa una carga moderada y recorrido cómodo.']),

  exercise('dominadas','Dominadas pronas','Espalda','Peso corporal',false,'Intermedio',['Cuelga con agarre prono y torso estable.','Lleva el pecho hacia la barra.','Desciende controlando hasta extensión completa.'],['Bíceps','Antebrazos'], 'Pull-ups', ['Balancear el cuerpo.','Encoger hombros hacia las orejas.'], ['Inicia deprimiendo las escápulas.']),
  exercise('remo-barra','Remo con barra','Espalda','Barra',true,'Intermedio',['Inclina el torso con espalda neutra.','Lleva la barra hacia el abdomen.','Baja hasta extender los brazos sin redondear la espalda.'],['Bíceps','Hombros'], 'Barbell row', ['Tirar con impulso lumbar.','Mirar demasiado arriba.'], ['Mantén el cuello alineado con la columna.']),
  exercise('jalon-polea','Jalón al pecho','Espalda','Polea',true,'Principiante',['Sujeta la barra con agarre amplio.','Baja hacia la parte alta del pecho.','Regresa con control manteniendo el torso estable.'],['Bíceps'], 'Lat pulldown', ['Llevar la barra detrás del cuello.','Inclinarse demasiado hacia atrás.'], ['Piensa en llevar los codos hacia abajo.']),

  exercise('press-militar','Press militar de pie','Hombros','Barra',true,'Intermedio',['Sujeta la barra a la altura de clavículas.','Aprieta glúteos y abdomen.','Empuja verticalmente y pasa la cabeza bajo la barra.'],['Tríceps','Core'], 'Overhead press', ['Arquear demasiado la zona lumbar.','Empujar la barra hacia delante.'], ['Mantén las costillas abajo.']),
  exercise('elevaciones-laterales','Elevaciones laterales','Hombros','Mancuernas',true,'Principiante',['Sostén mancuernas junto a los muslos.','Eleva los brazos hasta la altura de hombros.','Desciende de forma lenta.'],['Trapecio'], 'Laterales', ['Usar impulso.','Elevar por encima de los hombros.'], ['Guía con los codos y usa poco peso.']),
  exercise('face-pull','Face pull','Hombros','Polea',true,'Principiante',['Ajusta la polea a la altura del rostro.','Tira de la cuerda hacia la frente.','Abre las manos y junta las escápulas.'],['Espalda','Trapecio'], 'Tirón facial', ['Elevar hombros.','Tirar con la zona lumbar.'], ['Termina con los pulgares detrás de las orejas.']),

  exercise('curl-barra','Curl con barra','Bíceps','Barra',true,'Principiante',['Sujeta la barra con palmas arriba.','Flexiona los codos sin mover los hombros.','Baja hasta extender de forma controlada.'],['Antebrazos'], 'Barbell curl', ['Balancear la espalda.','Adelantar los codos.'], ['Mantén los codos cerca del torso.']),
  exercise('curl-martillo','Curl martillo','Bíceps','Mancuernas',true,'Principiante',['Sujeta mancuernas con agarre neutro.','Flexiona ambos codos manteniendo las muñecas rectas.','Baja con control.'],['Antebrazos'], 'Hammer curl', ['Girar las muñecas.','Subir los hombros.'], ['Evita el impulso con las piernas.']),
  exercise('curl-band','Curl con banda','Bíceps','Bandas',true,'Principiante',['Pisa el centro de la banda.','Sujeta los extremos con palmas arriba.','Flexiona los codos contra la tensión.'],['Antebrazos'], 'Curl elástico', ['Soltar tensión al bajar.','Separar codos del cuerpo.'], ['Elige una banda que permita control completo.']),

  exercise('fondos-banco','Fondos en banco','Tríceps','Peso corporal',false,'Principiante',['Apoya las manos en el borde de un banco.','Baja flexionando los codos hacia atrás.','Empuja hasta extender los brazos.'],['Hombros'], 'Bench dips', ['Bajar con hombros adelantados.','Abrir los codos.'], ['Mantén el pecho abierto y el recorrido cómodo.']),
  exercise('extension-polea','Extensión de tríceps en polea','Tríceps','Polea',true,'Principiante',['Sujeta la barra con codos pegados al cuerpo.','Extiende los codos hacia abajo.','Regresa sin mover los hombros.'],['Antebrazos'], 'Pushdown', ['Mover los codos hacia delante.','Inclinarse en exceso.'], ['Pausa un instante al final de la extensión.']),
  exercise('press-frances','Press francés','Tríceps','Mancuernas',true,'Intermedio',['Acuéstate y sostiene mancuernas sobre el pecho.','Flexiona los codos llevando el peso cerca de la frente.','Extiende sin separar los codos.'],['Hombros'], 'Skull crusher', ['Abrir los codos.','Descender sin control.'], ['Usa agarre neutro si los codos son sensibles.']),

  exercise('curl-muneca','Curl de muñeca','Antebrazos','Mancuernas',true,'Principiante',['Apoya antebrazos sobre los muslos.','Deja bajar la muñeca con control.','Flexiónala hasta cerrar la mano.'],['Bíceps'], 'Wrist curl', ['Mover todo el antebrazo.','Usar demasiado peso.'], ['Prioriza recorrido y control.']),
  exercise('paseo-granjero','Paseo del granjero','Antebrazos','Mancuernas',true,'Principiante',['Sujeta cargas a ambos lados.','Camina erguido con pasos cortos.','Mantén el agarre firme hasta completar la distancia.'],['Core','Trapecio'], 'Farmer walk', ['Inclinar el torso.','Caminar demasiado rápido.'], ['Mantén hombros abajo y cuello largo.']),
  exercise('colgar-barra','Colgarse de barra','Antebrazos','Sin equipamiento',false,'Principiante',['Sujeta una barra con agarre firme.','Cuelga con hombros activos.','Mantén la posición el tiempo pautado.'],['Espalda','Hombros'], 'Dead hang', ['Relajar completamente los hombros.','Balancearse.'], ['Empieza con intervalos cortos.']),

  exercise('sentadilla-barra','Sentadilla con barra','Cuádriceps','Barra',true,'Intermedio',['Apoya la barra sobre la parte alta de la espalda.','Desciende llevando cadera atrás y rodillas alineadas.','Empuja el suelo para subir.'],['Glúteos','Core'], 'Back squat', ['Colapsar las rodillas hacia dentro.','Perder la espalda neutra.'], ['Mantén el peso repartido en todo el pie.']),
  exercise('zancadas','Zancadas alternas','Cuádriceps','Peso corporal',false,'Principiante',['Da un paso largo hacia delante.','Baja ambas rodillas hacia el suelo.','Empuja con el pie delantero y alterna.'],['Glúteos','Isquiotibiales'], 'Lunges', ['Paso demasiado corto.','Inclinar el tronco.'], ['Mantén la rodilla delantera siguiendo al pie.']),
  exercise('prensa-piernas','Prensa de piernas','Cuádriceps','Máquina',true,'Principiante',['Coloca los pies al ancho de hombros.','Baja la plataforma con control.','Empuja sin bloquear las rodillas.'],['Glúteos'], 'Leg press', ['Despegar la cadera del asiento.','Bloquear rodillas al final.'], ['Usa un rango que mantenga la espalda apoyada.']),

  exercise('peso-muerto-rumano','Peso muerto rumano','Isquiotibiales','Barra',true,'Intermedio',['Sujeta la barra cerca de los muslos.','Lleva la cadera atrás con rodillas suaves.','Extiende la cadera para volver arriba.'],['Glúteos','Espalda'], 'RDL', ['Redondear la espalda.','Convertirlo en sentadilla.'], ['Mantén la barra pegada a las piernas.']),
  exercise('curl-femoral','Curl femoral tumbado','Isquiotibiales','Máquina',true,'Principiante',['Ajusta el rodillo sobre los tobillos.','Flexiona las rodillas llevando talones hacia glúteos.','Regresa controlando.'],['Pantorrillas'], 'Leg curl', ['Elevar la cadera.','Golpear el peso al bajar.'], ['Aprieta el abdomen contra el banco.']),
  exercise('puente-talones','Puente de isquiotibiales','Isquiotibiales','Sin equipamiento',false,'Principiante',['Túmbate boca arriba con talones cerca de glúteos.','Eleva la cadera apretando glúteos.','Acerca los talones para aumentar la tensión posterior.'],['Glúteos','Core'], 'Hamstring bridge', ['Arquear la espalda.','Empujar con las puntas de los pies.'], ['Presiona con los talones.']),

  exercise('hip-thrust','Hip thrust con barra','Glúteos','Barra',true,'Intermedio',['Apoya la espalda alta en un banco.','Empuja con talones elevando la cadera.','Pausa arriba con pelvis neutra.'],['Isquiotibiales','Cuádriceps'], 'Empuje de cadera', ['Hiperextender la zona lumbar.','Empujar con puntas de pies.'], ['Mira al frente y mantén costillas abajo.']),
  exercise('sentadilla-goblet','Sentadilla goblet','Glúteos','Kettlebell',true,'Principiante',['Sostén la kettlebell frente al pecho.','Desciende entre las caderas.','Sube empujando el suelo.'],['Cuádriceps','Core'], 'Goblet squat', ['Dejar caer el pecho.','Juntar rodillas.'], ['Usa los codos como guía para abrir las rodillas.']),
  exercise('patada-gluteo','Patada de glúteo','Glúteos','Bandas',true,'Principiante',['Coloca la banda sobre las rodillas o tobillos.','Extiende una pierna atrás sin girar la cadera.','Regresa lento y alterna.'],['Core','Isquiotibiales'], 'Kickback', ['Arquear la espalda.','Abrir la cadera.'], ['Mantén el abdomen firme.']),

  exercise('elevacion-talones','Elevación de talones de pie','Pantorrillas','Peso corporal',false,'Principiante',['Ponte de pie con pies paralelos.','Eleva los talones al máximo.','Baja de forma lenta hasta estirar.'],['Sóleo'], 'Calf raise', ['Rebotar abajo.','Doblar demasiado las rodillas.'], ['Pausa arriba un segundo.']),
  exercise('gemelo-maquina','Gemelo en máquina','Pantorrillas','Máquina',true,'Principiante',['Ajusta hombros bajo las almohadillas.','Eleva los talones de forma controlada.','Desciende hasta sentir estiramiento.'],['Sóleo'], 'Standing calf machine', ['Usar rebote.','Acortar recorrido.'], ['Trabaja lento en la fase baja.']),
  exercise('gemelo-sentado','Gemelo sentado','Pantorrillas','Mancuernas',true,'Principiante',['Siéntate con una mancuerna sobre las rodillas.','Eleva talones apoyando las puntas.','Baja completamente.'],['Sóleo'], 'Seated calf raise', ['Mover las rodillas.','Acelerar la bajada.'], ['Usa un soporte bajo los pies si es posible.']),

  exercise('plancha','Plancha frontal','Core/Abdominales','Sin equipamiento',false,'Principiante',['Apoya antebrazos y puntas de pies.','Forma una línea recta con el cuerpo.','Mantén la posición respirando con calma.'],['Hombros','Glúteos'], 'Plank', ['Elevar o hundir la cadera.','Contener la respiración.'], ['Aprieta abdomen y glúteos.']),
  exercise('crunch-polea','Crunch en polea','Core/Abdominales','Polea',true,'Intermedio',['Arrodíllate frente a una polea alta.','Flexiona el tronco llevando costillas hacia cadera.','Regresa controlando sin tirar con los brazos.'],['Oblicuos'], 'Cable crunch', ['Mover solo las caderas.','Tirar con los brazos.'], ['Piensa en cerrar las costillas.']),
  exercise('dead-bug','Dead bug','Core/Abdominales','Sin equipamiento',false,'Principiante',['Túmbate boca arriba con brazos arriba y rodillas a 90 grados.','Extiende pierna y brazo contrarios.','Vuelve sin despegar la zona lumbar.'],['Flexores de cadera'], 'Bicho muerto', ['Arquear la espalda.','Mover demasiado rápido.'], ['Exhala al extender.']),

  exercise('burpee','Burpee','Cuerpo completo','Peso corporal',false,'Intermedio',['Colócate en cuclillas y apoya manos.','Lleva pies atrás a plancha.','Regresa y realiza un salto suave.'],['Pecho','Cuádriceps','Core'], 'Burpees', ['Dejar caer la cadera en plancha.','Aterrizar con rodillas rígidas.'], ['Mantén un ritmo sostenible.']),
  exercise('swing-kettlebell','Swing con kettlebell','Cuerpo completo','Kettlebell',true,'Intermedio',['Lleva la kettlebell entre las piernas con bisagra de cadera.','Extiende cadera de forma explosiva.','Deja que la pesa vuelva guiada por la cadera.'],['Glúteos','Isquiotibiales','Core'], 'Kettlebell swing', ['Convertirlo en sentadilla.','Elevar con los brazos.'], ['La potencia nace de la cadera.']),
  exercise('thruster','Thruster con mancuernas','Cuerpo completo','Mancuernas',true,'Avanzado',['Lleva mancuernas a hombros.','Haz una sentadilla controlada.','Usa el impulso al subir para presionar sobre la cabeza.'],['Cuádriceps','Hombros','Tríceps'], 'Sentadilla a press', ['Perder la posición del tronco.','Presionar antes de extender cadera.'], ['Coordina la extensión de piernas y brazos.'])
];

EXERCISES.forEach(item => {
  item.relatedVariants = EXERCISES.filter(other => other.primaryMuscle === item.primaryMuscle && other.id !== item.id).slice(0, 2).map(other => other.name);
});
