/* Biblioteca, personalización y cargador de módulos de Dulus Gym Track. */
const exerciseState={query:'',muscle:'',weighted:'',equipment:'Todos'};
const escapeExerciseText=value=>String(value??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const findExercise=id=>EXERCISES.find(x=>String(x.id)===String(id));
const filteredExercises=()=>EXERCISES.filter(x=>{const q=exerciseState.query.toLocaleLowerCase('es'),text=`${x.name} ${x.alternativeName} ${x.primaryMuscle} ${x.equipment}`.toLocaleLowerCase('es');return(!q||text.includes(q))&&(!exerciseState.muscle||x.primaryMuscle===exerciseState.muscle)&&(!exerciseState.weighted||String(x.weighted)===exerciseState.weighted)&&(exerciseState.equipment==='Todos'||x.equipment===exerciseState.equipment)});
const exerciseCard=x=>`<button class="exercise-card" type="button" data-exercise-id="${x.id}"><span class="exercise-card-icon">${x.weighted?'◈':'○'}</span><span class="exercise-card-copy"><strong>${escapeExerciseText(x.name)}</strong><small>${escapeExerciseText(x.primaryMuscle)} · ${escapeExerciseText(x.equipment)}</small></span><span class="exercise-card-level ${x.level.toLowerCase()}">${escapeExerciseText(x.level)}</span><span class="exercise-card-arrow">›</span></button>`;
function renderEquipmentFilters(){document.querySelector('#equipment-filters').innerHTML=EXERCISE_EQUIPMENT.map(x=>`<button class="equipment-chip${exerciseState.equipment===x?' active':''}" type="button" data-equipment="${x}">${x}</button>`).join('');document.querySelectorAll('[data-equipment]').forEach(b=>b.onclick=()=>{exerciseState.equipment=b.dataset.equipment;renderExerciseLibrary()})}
function renderExerciseLibrary(){const list=filteredExercises();document.querySelector('#exercise-count').textContent=`${list.length} ${list.length===1?'ejercicio encontrado':'ejercicios encontrados'}`;document.querySelector('#exercise-list').innerHTML=list.length?list.map(exerciseCard).join(''):'<div class="exercise-empty">No encontramos ejercicios con esos filtros. Prueba otra búsqueda.</div>';document.querySelectorAll('[data-exercise-id]').forEach(b=>b.onclick=()=>openExerciseDetail(b.dataset.exerciseId));renderEquipmentFilters()}
const listMarkup=items=>`<ul class="exercise-detail-list">${items.map(x=>`<li>${escapeExerciseText(x)}</li>`).join('')}</ul>`;
const detailSection=(title,items)=>`<section class="exercise-detail-section"><h3>${title}</h3>${listMarkup(items)}</section>`;
function openExerciseDetail(id){const x=findExercise(id);if(!x)return;const media=x.media.image||x.media.video?'<div class="exercise-media-ready">Contenido demostrativo disponible próximamente.</div>':`<div class="exercise-tech-visual"><div class="tech-figure"><span class="tech-head"></span><span class="tech-body"></span><span class="tech-arm left"></span><span class="tech-arm right"></span><span class="tech-leg left"></span><span class="tech-leg right"></span></div><div><strong>Guía de ejecución</strong><p>${escapeExerciseText(x.instructions[0]||'Revisa la técnica antes de comenzar.')}</p><small>Próximamente: imagen o video real del movimiento.</small></div></div>`;document.querySelector('#exercise-detail').innerHTML=`<article class="exercise-detail-hero"><div><p class="label">${escapeExerciseText(x.primaryMuscle)} · ${escapeExerciseText(x.type)}</p><h2 id="exercise-detail-title">${escapeExerciseText(x.name)}</h2>${x.alternativeName?`<p class="exercise-alternative">${escapeExerciseText(x.alternativeName)}</p>`:''}</div><span class="exercise-card-level ${x.level.toLowerCase()}">${escapeExerciseText(x.level)}</span></article>${media}<section class="exercise-meta"><div><span>MÚSCULO PRINCIPAL</span><strong>${escapeExerciseText(x.primaryMuscle)}</strong></div><div><span>EQUIPAMIENTO</span><strong>${escapeExerciseText(x.equipment)}</strong></div><div><span>CARGA</span><strong>${x.weighted?'Con pesas':'Sin pesas'}</strong></div></section>${detailSection('Músculos trabajados',[x.primaryMuscle,...x.secondaryMuscles])}${detailSection('Instrucciones paso a paso',x.instructions)}${detailSection('Errores comunes',x.commonErrors)}${detailSection('Consejos de técnica',x.techniqueTips)}<section class="exercise-detail-section"><h3>Variantes relacionadas</h3><div class="variant-list">${x.relatedVariants.map(v=>`<span>${escapeExerciseText(v)}</span>`).join('')}</div></section>`;switchScreen('library-detail')}
function setupExerciseLibrary(){const muscle=document.querySelector('#exercise-muscle-filter');muscle.insertAdjacentHTML('beforeend',EXERCISE_MUSCLES.map(x=>`<option value="${x}">${x}</option>`).join(''));document.querySelector('#open-exercise-library').onclick=()=>{renderExerciseLibrary();switchScreen('library')};document.querySelector('#exercise-search').oninput=e=>{exerciseState.query=e.target.value.trim();renderExerciseLibrary()};muscle.onchange=e=>{exerciseState.muscle=e.target.value;renderExerciseLibrary()};document.querySelector('#exercise-load-filter').onchange=e=>{exerciseState.weighted=e.target.value;renderExerciseLibrary()};renderExerciseLibrary()}
const DULUS_GOALS=['Perder grasa','Ganar masa muscular','Mejorar fuerza','Mejorar resistencia','Mejorar movilidad','Aumentar glúteos','Definir abdomen','Tonificar cuerpo','Mejorar rendimiento deportivo','Aumentar explosividad','Mejorar velocidad','Recomposición corporal','Mejorar salud general'];
const DULUS_MESSAGES=[{motivation:'La disciplina de hoy construye la versión fuerte de mañana.',verse:'Todo lo puedo en Cristo que me fortalece.',ref:'Filipenses 4:13'},{motivation:'No necesitas ser perfecto; necesitas volver a cumplir hoy.',verse:'Los que esperan en el Señor renovarán sus fuerzas.',ref:'Isaías 40:31'},{motivation:'Cada repetición con intención cuenta. Sigue avanzando.',verse:'Esfuérzate y sé valiente; no temas ni desmayes.',ref:'Josué 1:9'},{motivation:'La constancia transforma lo difícil en parte de tu rutina.',verse:'Corramos con perseverancia la carrera que tenemos por delante.',ref:'Hebreos 12:1'}];
const motivationEnabled=()=>localStorage.getItem('dulus:motivation-enabled')!=='false';
function dailyMessage(){const d=new Date(),n=Number(`${d.getFullYear()}${String(d.getMonth()+1).padStart(2,'0')}${String(d.getDate()).padStart(2,'0')}`);return DULUS_MESSAGES[n%DULUS_MESSAGES.length]}
function motivationMarkup(extra=''){if(!motivationEnabled())return'';const x=dailyMessage();return`<article class="dulus-inspiration ${extra}"><span class="inspiration-icon">✦</span><div><p class="inspiration-kicker">FUERZA PARA HOY</p><strong>${escapeExerciseText(x.motivation)}</strong><blockquote>“${escapeExerciseText(x.verse)}” <span>— ${escapeExerciseText(x.ref)}</span></blockquote></div></article>`}
function refreshMotivation(){document.querySelectorAll('.dulus-inspiration').forEach(n=>n.remove());if(!motivationEnabled())return;document.querySelector('#screen-home .hero-card')?.insertAdjacentHTML('afterend',motivationMarkup('home-inspiration'));document.querySelector('#student-detail .detail-hero')?.insertAdjacentHTML('afterend',motivationMarkup('student-inspiration'))}
function setupMotivationSettings(){const p=document.querySelector('#screen-profile');if(!p||p.querySelector('#motivation-toggle'))return;p.insertAdjacentHTML('beforeend',`<section class="dulus-settings-card"><div><p class="label">PERSONALIZACIÓN</p><h3>Motivación y verso bíblico</h3><p>Muestra un mensaje al iniciar y también en la ficha del alumno.</p></div><label class="dulus-switch"><input id="motivation-toggle" type="checkbox" ${motivationEnabled()?'checked':''}><span></span></label></section>`);document.querySelector('#motivation-toggle').onchange=e=>{localStorage.setItem('dulus:motivation-enabled',String(e.target.checked));refreshMotivation()}}
function setupGoalSelector(){const form=document.querySelector('#student-form'),select=form?.querySelector('select[name="goal"]');if(!form||!select||form.querySelector('.goal-multi-field'))return;select.required=false;select.classList.add('sr-only');const label=select.closest('label');label.classList.add('legacy-goal-field');label.insertAdjacentHTML('afterend',`<fieldset class="goal-multi-field"><legend>Objetivos <small>Puedes seleccionar varios</small></legend><div class="goal-chip-grid">${DULUS_GOALS.map(g=>`<label class="goal-chip"><input type="checkbox" value="${g}"><span>${g}</span></label>`).join('')}</div><p class="goal-helper" id="goal-helper">Selecciona uno o varios objetivos para este alumno.</p></fieldset>`);const checks=[...form.querySelectorAll('.goal-chip input')];function sync(){const a=checks.filter(x=>x.checked).map(x=>x.value),value=a.join(' · ');select.querySelectorAll('[data-multi-goal]').forEach(x=>x.remove());if(value){const o=document.createElement('option');o.value=o.textContent=value;o.dataset.multiGoal='true';select.append(o);select.value=value}else select.value='';const h=document.querySelector('#goal-helper');if(h)h.textContent=a.length?`${a.length} objetivo${a.length===1?'':'s'} seleccionado${a.length===1?'':'s'}.`:'Selecciona uno o varios objetivos para este alumno.'}checks.forEach(x=>x.onchange=sync);form.addEventListener('reset',()=>setTimeout(()=>{checks.forEach(x=>x.checked=false);sync()},0));form.addEventListener('submit',e=>{sync();if(!checks.some(x=>x.checked)){e.preventDefault();e.stopImmediatePropagation();const h=document.querySelector('#goal-helper');h.textContent='Selecciona por lo menos un objetivo.';h.classList.add('error');form.querySelector('.goal-multi-field').scrollIntoView({behavior:'smooth',block:'center'})}},true)}
function updateLiveDate(){const k=document.querySelector('#page-kicker');if(k)k.textContent=new Intl.DateTimeFormat('es-DO',{weekday:'long',day:'numeric',month:'long'}).format(new Date()).toUpperCase()}
const detailTarget=document.querySelector('#student-detail');if(detailTarget)new MutationObserver(()=>{if(detailTarget.querySelector('.detail-hero')&&motivationEnabled()&&!detailTarget.querySelector('.student-inspiration'))detailTarget.querySelector('.detail-hero').insertAdjacentHTML('afterend',motivationMarkup('student-inspiration'))}).observe(detailTarget,{childList:true});
setupExerciseLibrary();setupGoalSelector();setupMotivationSettings();refreshMotivation();updateLiveDate();
const workoutModule=document.createElement('script');workoutModule.src='workouts.js';workoutModule.defer=true;document.body.appendChild(workoutModule);
