(() => {
'use strict';
const n=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
const avg=a=>a.length?a.reduce((s,x)=>s+x,0)/a.length:null;
const dateKey=d=>d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');
const daysBetween=(a,b)=>Math.floor((new Date(b+'T12:00:00')-new Date(a+'T12:00:00'))/86400000);
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
function adherence(student,plans,sessions){const own=plans.filter(p=>p.student_id===student.id),today=new Date();let due=0,done=0;for(let ago=1;ago<=14;ago++){const d=new Date(today);d.setDate(d.getDate()-ago);const key=dateKey(d);for(const p of own){if(p.start_date>key||!p.days?.includes(d.getDay()))continue;due++;const s=sessions.find(x=>x.plan_id===p.id&&x.date===key);if(s&&(s.completed_ids?.length||0)>=(s.total_exercises||Infinity))done++;}}return {due,done,rate:due?done/due:null};}
function trend(rows,key){const pts=rows.map(r=>({date:r.measured_on,value:key==='weight'?Number(r.weight_kg):Number(r.values_cm?.[key])})).filter(x=>Number.isFinite(x.value)).sort((a,b)=>String(a.date).localeCompare(String(b.date)));if(pts.length<2)return null;return {first:pts[0],last:pts.at(-1),change:pts.at(-1).value-pts[0].value,days:daysBetween(pts[0].date,pts.at(-1).date),count:pts.length};}
function build({api,student,plans,sessions,measurements,bodyGoals}){const ownPlans=plans.filter(p=>p.student_id===student.id),ownSessions=sessions.filter(s=>ownPlans.some(p=>p.id===s.plan_id)).sort((a,b)=>String(b.date).localeCompare(String(a.date))),rows=measurements.filter(r=>r.student_id===student.id).sort((a,b)=>String(a.measured_on).localeCompare(String(b.measured_on))),goal=bodyGoals.find(g=>g.student_id===student.id&&g.active),goalState=goal&&window.DulusBodyGoals?.goalState?.(goal,student,rows),ad=adherence(student,plans,sessions),progress=window.DulusProgress?.build?.(api,sessions,plans,[student]),muscles=progress?window.DulusProgress.studentMuscles(student.id,progress):[],strength=muscles.filter(m=>m.current!==null),up=strength.filter(m=>m.status==='Subiendo').length,down=strength.filter(m=>m.status==='Bajando').length;
 const recent=ownSessions.slice(0,3),fat=recent.map(s=>Number(s.details?.fatigue)).filter(Number.isFinite),pain=ownSessions.filter(s=>daysBetween(s.date,dateKey(new Date()))<=7).map(s=>Number(s.details?.pain||0)),avgFat=avg(fat),maxPain=pain.length?Math.max(...pain):0,goalText=norm((student.goals||[]).join(' '));
 const parts=[];const add=(key,label,state,detail,level)=>parts.push({key,label,state,detail,level});
 add('adherence','Constancia',ad.rate===null?'Sin calendario':Math.round(ad.rate*100)+'%',ad.due?ad.done+' de '+ad.due+' sesiones completas en 14 días.':'No hubo sesiones programadas en 14 días.',ad.rate===null?'neutral':ad.rate>=.8?'good':ad.rate>=.6?'watch':'attention');
 add('strength','Fuerza',!strength.length?'Sin e1RM':down?'Revisar tendencia':up?'Subiendo':'Estable / inicial',!strength.length?'Registra peso, repeticiones y RIR para medirla.':up+' grupos subiendo · '+down+' bajando.',down?'watch':up?'good':'neutral');
 let measureState='Opcional',measureDetail='No hay una meta corporal activa.';let measureLevel='neutral';if(goalState){measureState=goalState.reached?'Meta alcanzada':goalState.current===null?'Sin dato actual':Math.round(goalState.raw??0)+'% del trayecto';measureDetail=goalState.label+': '+(goalState.current===null?'—':goalState.current.toFixed(1))+' → '+goalState.target.toFixed(1)+' '+goalState.unit;measureLevel=goalState.reached?'good':goalState.goal.target_date&&goalState.goal.target_date<dateKey(new Date())?'watch':'neutral';}else if(/perder|grasa|definir|cintura/.test(goalText)){const t=trend(rows,'waist');if(t){measureState=t.change<=-.5?'Mejorando':'Sin cambio claro';measureDetail='Cintura '+(t.change>=0?'+':'')+t.change.toFixed(1)+' cm en '+t.days+' días.';measureLevel=t.change<=-.5?'good':'watch';}else{measureState='Falta tendencia';measureDetail='Registra cintura de forma periódica para este objetivo.';}}
 add('measures','Medidas',measureState,measureDetail,measureLevel);
 add('recovery','Recuperación',maxPain>=7?'Atención':maxPain>=4||avgFat>=8?'Revisar':recent.length?'Bien':'Sin datos',maxPain?('Dolor máximo reciente '+maxPain+'/10'+(avgFat!==null?' · fatiga media '+avgFat.toFixed(1)+'/10':'')):avgFat!==null?'Fatiga media '+avgFat.toFixed(1)+'/10.':'Sin feedback reciente.',maxPain>=7?'attention':maxPain>=4||avgFat>=8?'watch':recent.length?'good':'neutral');
 const needsBody=/perder|grasa|definir|cintura|gluteo|brazo|bicep|muslo|peso/.test(goalText)||!!goalState,bodyEnough=!needsBody||rows.length>=2,strengthEnough=strength.length>0,dataGood=ownSessions.length>=3&&(strengthEnough||bodyEnough);add('data','Calidad de datos',dataGood?'Suficiente':ownSessions.length?'En construcción':'Inicial',(ownSessions.length)+' sesiones registradas · '+strength.length+' grupos con e1RM · '+rows.length+' mediciones corporales.',dataGood?'good':'neutral');
 let focus='Mantener el plan y seguir registrando.';if(maxPain>=4||avgFat>=8)focus='Prioridad: recuperación y molestias antes de progresar carga.';else if(ad.rate!==null&&ad.rate<.6)focus='Prioridad: mejorar constancia o simplificar el plan.';else if(goalState&&goalState.goal.target_date&&goalState.goal.target_date<dateKey(new Date())&&!goalState.reached)focus='Prioridad: revisar si la meta corporal o su plazo siguen siendo realistas.';else if(down)focus='Prioridad: revisar los grupos musculares que están bajando antes de cambiar toda la rutina.';else if(!dataGood)focus='Prioridad: completar los datos mínimos que faltan; todavía no conviene sacar conclusiones fuertes.';
 return {student,parts,focus,goalState};}
function render({api,roster,plans,sessions,measurements,bodyGoals}){if(!roster.length)return null;const box=n('details',undefined,'objective-summary');box.open=!api.coach();box.append(n('summary','Resumen de avance según objetivo'));const head=n('div',undefined,'objective-summary-head'),select=n('select');let student=api.student?.()||roster[0];if(!roster.some(r=>r.id===student?.id))student=roster[0];if(api.coach()){const label=n('label','Alumno');for(const r of roster)select.append(new Option(r.name,r.id));select.value=student.id;label.append(select);head.append(label);}box.append(head);const body=n('div');box.append(body);
 function draw(){if(api.coach())student=roster.find(r=>r.id===select.value)||roster[0];const model=build({api,student,plans,sessions,measurements,bodyGoals});body.replaceChildren();const goal=n('p',student.goals?.length?'Objetivo: '+student.goals.join(' · '):'Sin objetivo general definido','objective-goal-line');body.append(goal);const grid=n('div',undefined,'objective-summary-grid');for(const part of model.parts){const card=n('article',undefined,'objective-summary-card');card.dataset.level=part.level;card.append(n('span',part.label),n('strong',part.state),n('small',part.detail));grid.append(card);}body.append(grid,n('p',model.focus,'objective-focus'));}
 select.onchange=draw;draw();return box;}
window.DulusObjectiveSummary={build,render};
})();
