(() => {
'use strict';
const metrics=[
 ['e1rm','Fuerza e1RM','kg','higher'],['vertical_jump','Salto vertical','cm','higher'],['broad_jump','Salto horizontal','cm','higher'],
 ['sprint_10m','Sprint 10 m','s','lower'],['sprint_20m','Sprint 20 m','s','lower'],['sprint_40m','Sprint 40 m','s','lower'],
 ['pullups','Dominadas máximas','reps','higher'],['plank','Plancha máxima','s','higher']
];
const manualMetrics=metrics.filter(x=>x[0]!=='e1rm');
const n=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
const b=(text,fn)=>{const e=n('button',text);e.type='button';e.onclick=fn;return e;};
const fmt=(x,d=1)=>Number.isFinite(Number(x))?Number(x).toFixed(d).replace(/\.0$/,''):'—';
const def=k=>metrics.find(x=>x[0]===k)||[k,k,'','higher'];
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
function progressData(student,api){return window.DulusProgress?.build?.({catalog:api.catalog},api.getSessions(),api.getPlans(),[student])||null;}
function e1rmCurrent(student,exerciseId,api,data){const d=data||progressData(student,api),series=d?.exerciseSeries?.get(student.id+':'+exerciseId);return series?.points?.at(-1)?.e1rm??null;}
function manualCurrent(metric,entries){return entries.filter(x=>x.metric===metric).sort((a,b)=>String(a.measured_on).localeCompare(String(b.measured_on))).at(-1)?.value??null;}
function currentValue(goal,student,entries,api,data){return goal.metric==='e1rm'?e1rmCurrent(student,goal.exercise_id,api,data):manualCurrent(goal.metric,entries);}
function goalState(goal,student,entries,api,data){const current=Number(currentValue(goal,student,entries,api,data)),start=Number(goal.start_value),target=Number(goal.target_value),[,,unit,direction]=def(goal.metric),hasCurrent=Number.isFinite(current)&&current>0,hasStart=Number.isFinite(start)&&start>0;let raw=null,reached=false;if(hasCurrent&&hasStart&&target!==start){raw=(current-start)/(target-start)*100;reached=direction==='lower'?current<=target:current>=target;}return {goal,current:hasCurrent?current:null,start:hasStart?start:null,target,unit,direction,raw,reached};}
function exerciseOptions(student,api,data){const ids=new Set();for(const p of api.getPlans().filter(p=>p.student_id===student.id))for(const x of p.exercises||[])ids.add(x.exerciseId);for(const s of data?.exerciseSeries?.values?.()||[])if(s.studentId===student.id)ids.add(s.exerciseId);return [...ids].map(id=>api.catalog.find(e=>e.id===id)).filter(Boolean).sort((a,b)=>a.name.localeCompare(b.name,'es'));}
function goalCard(goal,student,entries,api,data,rerender){const state=goalState(goal,student,entries,api,data),card=n('article',undefined,'performance-goal-card'),title=n('div',undefined,'body-goal-title');let label=def(goal.metric)[1];if(goal.metric==='e1rm'){const ex=api.catalog.find(e=>e.id===goal.exercise_id);label+=' · '+(ex?.name||'Ejercicio');}title.append(n('strong',label),n('span',goal.created_by===student.user_id?'Definida por alumno':'Definida por coach'));card.append(title);
 const values=n('div',undefined,'body-goal-values');for(const [v,l] of [[state.start!==null?fmt(state.start)+' '+state.unit:'—','Inicio'],[state.current!==null?fmt(state.current)+' '+state.unit:'—','Actual'],[fmt(state.target)+' '+state.unit,'Objetivo']]){const x=n('div');x.append(n('strong',v),n('small',l));values.append(x);}card.append(values);
 if(state.raw!==null){const progress=clamp(state.raw,0,100),bar=n('div',undefined,'body-goal-progress'),fill=n('span');fill.style.width=progress+'%';bar.append(fill);card.append(bar,n('small',fmt(state.raw,0)+'% del trayecto medido'+(state.reached?' · Meta alcanzada ✓':'')));}
 if(goal.target_date)card.append(n('small','Fecha objetivo: '+goal.target_date));if(goal.note)card.append(n('p',goal.note));const actions=n('div',undefined,'body-goal-actions'),close=b('Cerrar meta',()=>{}),remove=b('Eliminar meta',()=>{});let armed=false,timer=null;close.onclick=async()=>{if(!armed){armed=true;close.textContent='Confirmar cierre';clearTimeout(timer);timer=setTimeout(()=>{armed=false;close.textContent='Cerrar meta';},4000);return;}close.disabled=true;try{await api.check(api.db.rpc('dulus_close_performance_goal',{p_goal:goal.id}));await rerender();}catch{close.disabled=false;close.textContent='Reintentar';}};let removeArmed=false,removeTimer=null;remove.onclick=async()=>{if(!removeArmed){removeArmed=true;remove.textContent='Confirmar eliminación';clearTimeout(removeTimer);removeTimer=setTimeout(()=>{removeArmed=false;remove.textContent='Eliminar meta';},4000);return;}remove.disabled=true;try{await api.check(api.db.rpc('dulus_delete_performance_goal',{p_goal:goal.id}));await rerender();}catch{remove.disabled=false;remove.textContent='Reintentar';}};actions.append(close,remove);card.append(actions);return card;}
function testEditor(student,api,rerender){const form=n('form',undefined,'performance-test-form'),metricLabel=n('label','Prueba'),metric=n('select');for(const [k,l] of manualMetrics)metric.append(new Option(l,k));const valueLabel=n('label','Resultado'),value=n('input');value.type='number';value.step='.01';value.min='.01';value.required=true;const dateLabel=n('label','Fecha de la prueba'),date=n('input');date.type='date';date.max=new Date().toISOString().slice(0,10);date.value=date.max;date.required=true;const noteLabel=n('label','Nota (opcional)'),note=n('input');note.maxLength=500;const unit=n('small'),save=n('button','Guardar prueba');save.type='submit';metricLabel.append(metric);valueLabel.append(value);dateLabel.append(date);noteLabel.append(note);const sync=()=>{unit.textContent='Unidad: '+def(metric.value)[2];};metric.onchange=sync;sync();form.append(metricLabel,valueLabel,dateLabel,noteLabel,unit,save);form.onsubmit=async e=>{e.preventDefault();const v=Number(value.value),u=def(metric.value)[2];if(!(v>0))return;save.disabled=true;const {error}=await api.db.from('dulus_performance_entries').insert({student_id:student.id,metric:metric.value,value:v,unit:u,measured_on:date.value,note:note.value.trim()});if(error){unit.textContent=error.message||'No se pudo guardar.';save.disabled=false;return;}await rerender();};return form;}
function goalEditor(student,entries,api,data,rerender){const form=n('form',undefined,'performance-goal-form'),metricLabel=n('label','Tipo de meta'),metric=n('select');for(const [k,l] of metrics)metric.append(new Option(l,k));const exerciseLabel=n('label','Ejercicio'),exercise=n('select'),targetLabel=n('label','Objetivo'),target=n('input');target.type='number';target.step='.01';target.min='.01';target.required=true;const dateLabel=n('label','Fecha objetivo (opcional)'),date=n('input');date.type='date';date.min=new Date().toISOString().slice(0,10);const noteLabel=n('label','Nota (opcional)'),note=n('input');note.maxLength=500;const current=n('small'),save=n('button','Guardar meta');save.type='submit';metricLabel.append(metric);exerciseLabel.append(exercise);targetLabel.append(target);dateLabel.append(date);noteLabel.append(note);
 const sync=()=>{const isE1=metric.value==='e1rm';exerciseLabel.hidden=!isE1;exercise.replaceChildren();if(isE1){for(const e of exerciseOptions(student,api,data))exercise.append(new Option(e.name,e.id));if(!exercise.options.length)exercise.append(new Option('Primero registra/crea un ejercicio',''));}const fake={metric:metric.value,exercise_id:isE1?exercise.value:null},v=currentValue(fake,student,entries,api,data),u=def(metric.value)[2];current.textContent='Actual: '+(v?fmt(v)+' '+u:'sin dato todavía')+'. La fecha objetivo es opcional.';};metric.onchange=sync;exercise.onchange=sync;sync();form.append(metricLabel,exerciseLabel,targetLabel,dateLabel,noteLabel,current,save);
 form.onsubmit=async e=>{e.preventDefault();const isE1=metric.value==='e1rm',exerciseId=isE1?exercise.value:null;if(isE1&&!exerciseId){current.textContent='Selecciona un ejercicio que ya esté en la rutina.';return;}const fake={metric:metric.value,exercise_id:exerciseId},start=currentValue(fake,student,entries,api,data),value=Number(target.value),u=def(metric.value)[2];if(!(value>0))return;save.disabled=true;try{await api.check(api.db.rpc('dulus_save_performance_goal',{p_student:student.id,p_metric:metric.value,p_exercise:exerciseId,p_start:start,p_target:value,p_unit:u,p_date:date.value||null,p_note:note.value.trim()}));await rerender();}catch(err){current.textContent=err.message||'No se pudo guardar la meta.';save.disabled=false;}};return form;}
function history(entries,api,student,rerender){const box=n('div',undefined,'performance-history');box.append(n('h4','Pruebas recientes'));const rows=[...entries].sort((a,b)=>String(b.measured_on).localeCompare(String(a.measured_on))).slice(0,8);if(!rows.length){box.append(n('p','Aún no hay pruebas manuales registradas.'));return box;}for(const r of rows){const item=n('article'),copy=n('div'),remove=b('Eliminar',()=>{});copy.append(n('strong',def(r.metric)[1]+' · '+fmt(r.value)+' '+r.unit),n('small',r.measured_on+(r.note?' · '+r.note:'')));let armed=false,timer=null;remove.onclick=async()=>{if(!armed){armed=true;remove.textContent='Confirmar';clearTimeout(timer);timer=setTimeout(()=>{armed=false;remove.textContent='Eliminar';},4000);return;}remove.disabled=true;const {error}=await api.db.from('dulus_performance_entries').delete().eq('id',r.id);if(error){remove.disabled=false;remove.textContent='Reintentar';return;}await rerender();};item.append(copy,remove);box.append(item);}return box;}
function dashboardSummary({student,goals,entries,api}){const data=progressData(student,api),own=goals.filter(g=>g.student_id===student.id&&g.active).map(g=>goalState(g,student,entries.filter(x=>x.student_id===student.id),api,data));if(!own.length)return null;const box=n('section',undefined,'performance-goal-dashboard');box.append(n('h3','Mis metas de rendimiento'));for(const state of own.slice(0,3)){let label=def(state.goal.metric)[1];if(state.goal.metric==='e1rm'){const ex=api.catalog.find(e=>e.id===state.goal.exercise_id);label+=' · '+(ex?.name||'Ejercicio');}const card=n('article'),line=state.current===null?'Actual sin dato':fmt(state.current)+' '+state.unit+' → '+fmt(state.target)+' '+state.unit;card.append(n('strong',label),n('p',line));if(state.raw!==null)card.append(n('small',fmt(state.raw,0)+'% del trayecto'+(state.reached?' · Meta alcanzada ✓':'')));else card.append(n('small','Registra datos para calcular progreso.'));box.append(card);}return box;}
window.DulusPerformanceGoals={metrics,currentValue,goalState,dashboardSummary,create(api){const host=document.getElementById('student-performance-goals');let current=null,token=0;async function load(student){const [entries,goals]=await Promise.all([api.check(api.db.from('dulus_performance_entries').select('*').eq('student_id',student.id).order('measured_on')),api.check(api.db.from('dulus_performance_goals').select('*').eq('student_id',student.id).eq('active',true).order('created_at'))]);return {entries,goals};}
 async function render(student){const id=++token;current=student;host.replaceChildren();const section=n('details',undefined,'performance-goals-section');section.append(n('summary','Metas de rendimiento · opcional'),n('p','Fuerza e1RM se calcula desde tus sesiones. Salto, sprint y pruebas físicas solo se registran cuando realmente las haces. La fecha objetivo es opcional.','progress-note'));host.append(section);let data;try{data=await load(student);}catch{if(id===token)section.append(n('p','No se pudieron cargar las metas de rendimiento.'));return;}if(id!==token||current?.id!==student.id)return;const strength=progressData(student,api),rerender=()=>render(student),active=n('div',undefined,'performance-goal-list');active.append(n('h4','Metas activas'));if(!data.goals.length)active.append(n('p','No hay metas de rendimiento activas. No es obligatorio crear una.'));for(const g of data.goals)active.append(goalCard(g,student,data.entries,api,strength,rerender));section.append(active);
 const addGoal=n('details',undefined,'performance-goal-create');addGoal.append(n('summary','Añadir meta de rendimiento'),goalEditor(student,data.entries,api,strength,rerender));const addTest=n('details',undefined,'performance-test-create');addTest.append(n('summary','Registrar una prueba física'),testEditor(student,api,rerender));section.append(addGoal,addTest,history(data.entries,api,student,rerender));}
 return {render,clear(){token++;current=null;host?.replaceChildren();}};}};
})();
