/* Private coach/student feedback. All database access uses the signed-in user's RLS. */
(() => {
'use strict';
const node=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
const button=(label,fn)=>{const e=node('button',label);e.type='button';e.onclick=fn;return e;};
const number=(label,value,min,max)=>{const box=node('label',label),input=node('input');Object.assign(input,{type:'number',min:String(min),max:String(max),step:'1',value:value??''});box.append(input);return {box,input};};
const read=k=>{try{return JSON.parse(localStorage.getItem(k)||'null');}catch{return null;}};
window.DulusBridge={create(api){
 let current=null,logs={},feedback={},key='',generation=0,channel=null,subUser=null,feedBusy=false,openMessages=null;
 const db=api.db,check=async p=>{const {data,error}=await p;if(error)throw error;return data;};


 let retentionEnabled=false;
 async function refreshRetention(){try{const result=await check(db.rpc('dulus_video_retention_status'));retentionEnabled=result?.enabled===true;}catch{retentionEnabled=false;}}
 const retentionText=()=>retentionEnabled?'Se borra automáticamente a los 7 días. Conserva el original. La limpieza se realiza cada hora.':'Conserva el original. La limpieza automática de videos aún no está activada.';
 function videoExpiry(m){const date=new Date(m.created_at).getTime();return Number.isFinite(date)?date+7*86400000:null;}

 let uploading=false,videoOwner=null;
 const uploadPanel=node('section',undefined,'video-upload-panel');uploadPanel.hidden=true;uploadPanel.id='video-upload-panel';uploadPanel.setAttribute('aria-label','Estado del envío de video');
 const uploadTitle=node('strong'),uploadFile=node('p'),uploadDescription=node('p'),uploadProgress=node('progress');uploadProgress.setAttribute('aria-label','Envío de video en curso');
 const uploadLive=node('div');uploadLive.setAttribute('role','status');uploadLive.setAttribute('aria-live','polite');uploadLive.setAttribute('aria-atomic','true');uploadLive.append(uploadTitle,uploadDescription);
 const dismissUpload=button('Cerrar aviso',()=>{if(!uploading)uploadPanel.hidden=true;});
 uploadPanel.append(uploadLive,uploadFile,uploadProgress,dismissUpload);document.body.append(uploadPanel);
 function videoState(state,title,description,video){if(videoOwner!==api.user()){uploadPanel.hidden=true;return;}uploadPanel.hidden=false;uploadPanel.dataset.state=state;uploadTitle.textContent=title;uploadDescription.textContent=description;uploadProgress.hidden=state!=='uploading';dismissUpload.disabled=state==='uploading';if(video)uploadFile.textContent=video.name+' · '+(video.size/1024/1024).toFixed(1)+' MB';}
 db.auth.onAuthStateChange?.(event=>{if(event==='SIGNED_OUT'){uploadPanel.hidden=true;videoOwner=null;}});

 const dashboard=node('section',undefined,'bridge-dashboard dulus-settings-card');dashboard.id='bridge-dashboard';document.getElementById('team-content').prepend(dashboard);
 const status=node('p');status.setAttribute('role','status');
 const theme=button('Modo claro',()=>{const light=document.body.dataset.teamTheme!=='light';document.body.dataset.teamTheme=light?'light':'dark';theme.textContent=light?'Modo oscuro':'Modo claro';try{localStorage.setItem('dulus-team-theme',light?'light':'dark');}catch{}});
 let savedTheme;try{savedTheme=localStorage.getItem('dulus-team-theme');}catch{}document.body.dataset.teamTheme=savedTheme==='light'?'light':'dark';theme.textContent=savedTheme==='light'?'Modo oscuro':'Modo claro';document.querySelector('.topbar').append(theme);
 function persist(){try{localStorage.setItem(key,JSON.stringify({logs,feedback}));}catch{}}
 function open(plan,date){generation++;current=plan;key='dulus-feedback:'+api.user()+':'+plan.id+':'+date;const saved=read(key)||{};logs=saved.logs||{};feedback=saved.feedback||{};openMessages=null;}
 function feedbackView(){const section=node('section',undefined,'session-feedback');section.append(node('h3','¿Cómo te fue hoy?'),node('p',api.solo?.()?'Opcional · Guarda cómo te sentiste para entender tu progreso.':'Opcional · Cuéntaselo a tu coach al guardar.'));let painInput=null;
 for(const [id,label,min] of [['effort','Esfuerzo percibido · 1 a 10',1],['fatigue','Fatiga · 0 a 10',0],['pain','Dolor · 0 a 10',0]]){const f=number(label,feedback[id],min,10);f.input.oninput=()=>{feedback[id]=f.input.value===''?null:Number(f.input.value);if(id==='pain'&&!(feedback[id]>0)){feedback.painLocation='';feedback.painNote='';}persist();if(id==='pain')syncPain();};if(id==='pain')painInput=f.input;section.append(f.box);}
 const painExtra=node('div',undefined,'pain-extra'),locLabel=node('label','Zona de la molestia (opcional)'),loc=node('select');for(const v of ['', 'Rodilla','Tobillo / pie','Pantorrilla / sóleo','Isquiotibiales','Cuádriceps','Cadera / glúteo','Espalda baja','Espalda alta','Hombro','Codo','Muñeca / mano','Pecho','Cuello','Otro'])loc.append(new Option(v||'Selecciona una zona',v));loc.value=feedback.painLocation||'';loc.onchange=()=>{feedback.painLocation=loc.value;persist();};locLabel.append(loc);const noteLabel=node('label','Nota sobre la molestia (opcional)'),note=node('textarea');note.maxLength=300;note.rows=2;note.value=feedback.painNote||'';note.placeholder='Ej.: aparece al aterrizar o al final de la sesión.';note.oninput=()=>{feedback.painNote=note.value.trimStart();persist();};noteLabel.append(note);painExtra.append(node('small','No es un diagnóstico. Sirve para que tú y tu coach identifiquen si una molestia se repite.'),locLabel,noteLabel);section.append(painExtra);function syncPain(){painExtra.hidden=!(Number(painInput?.value)>0);}syncPain();return section;}
 function exerciseView(plan,item){const section=node('section',undefined,'exercise-connection'),entry=logs[item.exerciseId]||(logs[item.exerciseId]={exerciseId:item.exerciseId,weightKg:item.weightKg??null,reps:item.reps,rir:null});
 const loads=node('details');loads.append(node('summary','Ajustar mi carga · RIR'),node('p','Registra lo que hiciste. RIR es cuántas repeticiones más crees que podrías haber hecho. El coach verá los cambios al guardar.'));
 for(const [id,label,min,max] of [['weightKg','Peso realizado (kg)',0,1000],['reps','Repeticiones realizadas por serie',1,100],['rir','Repeticiones en reserva · RIR',0,10]]){const f=number(label,entry[id],min,max);if(id==='weightKg')f.input.step='0.5';f.input.oninput=()=>{entry[id]=f.input.value===''?null:Number(f.input.value);persist();};loads.append(f.box);}
 section.append(loads);if(api.solo?.())return section;
 const chat=node('details',undefined,'exercise-chat');chat.append(node('summary','Hablar con mi coach · este ejercicio'));
 const messages=node('div'),message=node('textarea');message.maxLength=2000;message.value=entry.commentDraft||'';message.oninput=()=>{entry.commentDraft=message.value;persist();};message.placeholder='Una duda, una molestia o un comentario…';message.setAttribute('aria-label','Mensaje sobre este ejercicio');
 const info=node('p');info.setAttribute('role','status');const token=generation;
 async function reload(){try{await refreshRetention();const rows=await check(db.from('dulus_messages').select('*').eq('plan_id',plan.id).eq('exercise_id',item.exerciseId).order('created_at',{ascending:true}).limit(100));if(token!==generation)return;messages.replaceChildren();for(const m of rows||[]){const line=node('article',undefined,'message');line.append(node('small',m.author_id===api.user()?'Tú':'Coach / alumno'),node('p',m.body));if(m.video_path){const expiry=videoExpiry(m),expired=retentionEnabled&&expiry!==null&&Date.now()>=expiry;
 line.append(node('small',expired?'Video caducado · Los comentarios se conservan.':retentionEnabled&&expiry!==null?'Disponible hasta '+new Date(expiry).toLocaleString('es')+'. Conserva el original.':retentionText()));
 if(!expired)line.append(button('Ver video privado',async()=>{try{if(retentionEnabled&&expiry!==null&&Date.now()>=expiry){info.textContent='El video ha caducado. Los comentarios se conservan.';await reload();return;}const ttl=retentionEnabled&&expiry!==null?Math.max(1,Math.min(300,Math.floor((expiry-Date.now())/1000))):300;const data=await check(db.storage.from('dulus-technique').createSignedUrl(m.video_path,ttl));const v=node('video');v.controls=true;v.playsInline=true;v.src=data.signedUrl;line.append(v);}catch{info.textContent='No se pudo abrir el video. Puede haber caducado; los comentarios se conservan.';}}));}messages.append(line);}if(!rows?.length)messages.append(node('p','Aún no hay comentarios.'));}catch{info.textContent='No se pudieron cargar los comentarios. Puedes reintentar.';}}
 const send=button('Enviar comentario',async()=>{if(!message.value.trim())return;send.disabled=true;try{await check(db.from('dulus_messages').insert({plan_id:plan.id,exercise_id:item.exerciseId,author_id:api.user(),body:message.value.trim()}));message.value='';entry.commentDraft='';persist();info.textContent='Comentario compartido.';await reload();}catch{info.textContent='No se pudo enviar. Tu texto sigue aquí.';}finally{send.disabled=false;}});
 const file=node('input');file.type='file';file.accept='video/mp4,video/webm,video/quicktime';file.setAttribute('capture','environment');file.hidden=true;
 const camera=button('📹 Grabar técnica',()=>file.click());camera.className='technique-camera';camera.setAttribute('aria-label','Grabar técnica para mi coach');
 file.onchange=async()=>{
 const video=file.files?.[0];if(!video)return;if(uploading){uploadPanel.hidden=false;file.value='';return;}
 videoOwner=api.user();
 if(video.size===0||video.size>20*1024*1024||!['video/mp4','video/webm','video/quicktime'].includes(video.type)){videoState('error','Video no enviado',video.size>20*1024*1024?'El archivo supera los 20 MB. Elige un clip más corto.':'Elige un archivo MP4, WebM o MOV válido de hasta 20 MB.',video);file.value='';return;}
 uploading=true;camera.disabled=true;info.textContent='';videoState('uploading','Subiendo video…','Mantén esta pestaña abierta. Puedes seguir viendo los ejercicios.',video);
 const path=plan.id+'/'+api.user()+'/'+crypto.randomUUID()+({'video/mp4':'.mp4','video/webm':'.webm','video/quicktime':'.mov'}[video.type]);let uploaded=false;
 try{
  await check(db.storage.from('dulus-technique').upload(path,video,{contentType:video.type,upsert:false}));uploaded=true;
  videoState('uploading','Compartiendo con tu coach…','El archivo ya subió. Estamos guardando el envío en este ejercicio.');
  await check(db.from('dulus_messages').insert({plan_id:plan.id,exercise_id:item.exerciseId,author_id:videoOwner,body:'Video de técnica para revisión',video_path:path}));
  uploading=false;videoState('success','Video enviado a tu coach.','✓ Envío confirmado. Tu coach puede verlo en la actividad del equipo. '+retentionText());file.value='';await reload();
 }catch(error){
  if(uploaded){try{await db.storage.from('dulus-technique').remove([path]);}catch{}}
  uploading=false;videoState('error','No se pudo confirmar el envío','Revisa tu conexión y los comentarios antes de intentarlo de nuevo. Conserva el archivo original.');
 }finally{uploading=false;camera.disabled=false;file.value='';}
};
 chat.append(messages,message,send,node('small','Al grabar o elegir un video, se envía a este espacio privado con tu coach. Máximo 20 MB. '+retentionText()),info,button('Actualizar comentarios',reload));
 chat.ontoggle=()=>{if(chat.open){openMessages=reload;reload();}};section.append(chat,camera,file,info);return section;}
 function snapshot(completed){const exercises=Object.values(logs).filter(x=>!completed||completed.includes(x.exerciseId));for(const x of exercises){if(x.weightKg!==null&&(!Number.isFinite(x.weightKg)||x.weightKg<0||x.weightKg>1000)||x.reps!==null&&(!Number.isInteger(x.reps)||x.reps<1||x.reps>100)||x.rir!==null&&(!Number.isInteger(x.rir)||x.rir<0||x.rir>10))throw Error('Revisa el peso, las repeticiones y el RIR.');}return {...feedback,exercises:exercises.map(({commentDraft,...x})=>x)};}
 function coachInbox(uid,plans,roster,sessions,messages){
 const section=node('section',undefined,'coach-inbox');if(!api.coach())return section;const store='dulus-coach-seen:'+uid+':'+api.team(),seen=new Set(read(store)||[]),alerts=[];
 for(const m of messages||[]){if(m.author_id===uid)continue;const p=plans.find(x=>x.id===m.plan_id),student=roster.find(x=>x.id===p?.student_id);alerts.push({key:'message:'+m.id,time:m.created_at,priority:m.video_path?3:2,kind:m.video_path?'video':'message',title:m.video_path?'🎥 Video para revisión':'💬 Comentario nuevo',body:(student?.name||'Alumno')+' · '+(api.catalog.find(e=>e.id===m.exercise_id)?.name||'Ejercicio')+(m.video_path?'':': '+m.body),studentId:student?.id,plan:p,exercise:m.exercise_id,message:m});}
 for(const s of sessions||[]){const pain=Number(s.details?.pain||0);if(pain<=0)continue;const p=plans.find(x=>x.id===s.plan_id),student=roster.find(x=>x.id===p?.student_id);alerts.push({key:'pain:'+s.id,time:s.updated_at||s.date,priority:pain>=7?5:pain>=4?4:3,kind:'pain',title:'⚠️ Molestia reportada',body:(student?.name||'Alumno')+' · Dolor '+pain+'/10'+(s.details?.painLocation?' · '+s.details.painLocation:'')+' · '+(p?.name||'Rutina')+' · '+s.date,studentId:student?.id,plan:p,session:s});}
 alerts.sort((a,b)=>(seen.has(a.key)-seen.has(b.key))||(b.priority-a.priority)||String(b.time).localeCompare(String(a.time)));const head=node('div',undefined,'coach-inbox-head'),copy=node('div');copy.append(node('p','CENTRO DE AVISOS','eyebrow'),node('h3','Pendientes del coach'));const badge=node('span','','coach-inbox-badge');head.append(copy,badge);section.append(head);
 const label=node('label','Filtrar por alumno'),filter=node('select');filter.append(new Option('Todos los alumnos',''));for(const s of roster)filter.append(new Option(s.name,s.id));label.append(filter);section.append(label);const showReviewedLabel=node('label',undefined,'coach-inbox-show-reviewed'),showReviewed=node('input');showReviewed.type='checkbox';showReviewedLabel.append(showReviewed,node('span','Mostrar revisados'));section.append(showReviewedLabel);const list=node('div',undefined,'coach-inbox-list');section.append(list);
 const save=()=>{try{localStorage.setItem(store,JSON.stringify([...seen].slice(-500)));}catch{}};const refreshBadge=()=>{const n=alerts.filter(a=>!seen.has(a.key)).length;badge.textContent=n?n+' pendiente'+(n===1?'':'s'):'Sin pendientes';badge.dataset.empty=String(n===0);};
 function mark(a,card,buttonEl){seen.add(a.key);save();card.dataset.seen='true';if(buttonEl){buttonEl.textContent='Revisado ✓';buttonEl.disabled=true;}refreshBadge();}
 function draw(){list.replaceChildren();const rows=alerts.filter(a=>(!filter.value||a.studentId===filter.value)&&(showReviewed.checked||!seen.has(a.key)));if(!rows.length){list.append(node('p',showReviewed.checked?'No hay avisos para este filtro.':'No hay avisos pendientes para este filtro.'));return;}for(const a of rows){const card=node('article',undefined,'coach-alert coach-alert-'+a.kind);card.dataset.seen=String(seen.has(a.key));card.append(node('strong',a.title),node('p',a.body),node('small',new Date(String(a.time).length===10?a.time+'T12:00:00':a.time).toLocaleString('es')));if(a.kind==='video'){const view=button('Ver video privado',async()=>{view.disabled=true;try{const data=await check(db.storage.from('dulus-technique').createSignedUrl(a.message.video_path,300));const v=node('video');v.controls=true;v.playsInline=true;v.src=data.signedUrl;card.append(v);mark(a,card,review);}catch{view.disabled=false;view.textContent='Reintentar video';}});card.append(view);}if(a.kind==='pain'){const d=a.session.details||{};card.append(node('p','Esfuerzo '+(d.effort??'—')+'/10 · Fatiga '+(d.fatigue??'—')+'/10 · Dolor '+(d.pain??'—')+'/10'+(d.painLocation?' · '+d.painLocation:'')));if(d.painNote)card.append(node('p','Nota: '+d.painNote));}const actions=node('div',undefined,'coach-alert-actions'),studentBtn=button('Ver alumno',()=>{mark(a,card,review);api.select?.(a.studentId);document.getElementById('student-panel')?.scrollIntoView({behavior:'smooth',block:'start'});}),review=button(seen.has(a.key)?'Revisado ✓':'Marcar revisado',()=>{mark(a,card,review);if(!showReviewed.checked)draw();});review.disabled=seen.has(a.key);actions.append(studentBtn,review);card.append(actions);list.append(card);}}
 filter.onchange=draw;showReviewed.onchange=draw;refreshBadge();draw();return section;
}
 async function renderDashboard(){if(feedBusy||!api.user())return;feedBusy=true;const uid=api.user();try{
 const plans=api.plans(),roster=api.roster(),ids=plans.map(p=>p.id),studentIds=roster.map(r=>r.id);const sessions=ids.length?await check(db.from('dulus_sessions').select('*').in('plan_id',ids).order('date',{ascending:false})):[],messages=ids.length?await check(db.from('dulus_messages').select('*').in('plan_id',ids).order('created_at',{ascending:false}).limit(30)):[],checkins=studentIds.length?await check(db.from('dulus_checkins').select('*').in('student_id',studentIds).order('created_at',{ascending:false}).limit(50)):[],measurements=studentIds.length?await check(db.from('dulus_measurements').select('*').in('student_id',studentIds).order('measured_on')):[],bodyGoals=studentIds.length?await check(db.from('dulus_body_goals').select('*').in('student_id',studentIds).eq('active',true).order('created_at')):[],performanceGoals=studentIds.length?await check(db.from('dulus_performance_goals').select('*').in('student_id',studentIds).eq('active',true).order('created_at')):[],performanceEntries=studentIds.length?await check(db.from('dulus_performance_entries').select('*').in('student_id',studentIds).order('measured_on')):[],decisions=studentIds.length?await check(db.from('dulus_coach_decisions').select('*').in('student_id',studentIds).order('effective_on',{ascending:false}).order('created_at',{ascending:false})):[],snoozes=api.coach()&&studentIds.length?await check(db.from('dulus_agenda_snoozes').select('*').in('student_id',studentIds).gt('snoozed_until',new Date().toISOString())):[];
 if(uid!==api.user())return;dashboard.replaceChildren();dashboard.append(node('p',api.coach()?'TU EQUIPO, DE UN VISTAZO':'TU SEMANA','eyebrow'),node('h2',api.coach()?'Acompaña cada avance':'Cada entrenamiento cuenta'));if(api.coach()){const agenda=window.DulusCoachAgenda?.render({api,uid,teamId:api.team(),plans,roster,sessions,messages,measurements,bodyGoals,performanceGoals,performanceEntries,decisions,snoozes,db,refresh:renderDashboard});if(agenda)dashboard.append(agenda);const progression=window.DulusLoadProgression?.render({api,uid,plans,roster,sessions,db,reload:api.reload});if(progression)dashboard.append(progression);}const objectiveSummary=window.DulusObjectiveSummary?.render({api,roster,plans,sessions,measurements,bodyGoals,performanceGoals,performanceEntries});if(objectiveSummary)dashboard.append(objectiveSummary);const cycleReview=window.DulusCycleReview?.render({api,roster,plans,sessions,measurements,bodyGoals,performanceEntries,decisions});if(cycleReview)dashboard.append(cycleReview);if(api.coach()){const actionCenter=window.DulusCoachAction?.render({api,uid,teamId:api.team(),plans,roster,sessions,messages,measurements,bodyGoals,performanceGoals,performanceEntries,decisions,checkins,db,node,button});if(actionCenter)dashboard.append(actionCenter);dashboard.append(coachInbox(uid,plans,roster,sessions,messages));}
 if(!api.coach()&&roster[0]){const guidance=window.DulusStudentGuidance?.render({student:roster[0],plans,sessions,measurements,node});if(guidance)dashboard.append(guidance);const goalSummary=window.DulusBodyGoals?.dashboardSummary?.({student:roster[0],goals:bodyGoals,measurements});if(goalSummary)dashboard.append(goalSummary);const perfApi={catalog:api.catalog,getPlans:()=>plans,getSessions:()=>sessions},perfSummary=window.DulusPerformanceGoals?.dashboardSummary?.({student:roster[0],goals:performanceGoals,entries:performanceEntries,api:perfApi});if(perfSummary)dashboard.append(perfSummary);const trackingSchedule=window.DulusTrackingSchedule?.render?.({student:roster[0],measurements,performanceEntries,node});if(trackingSchedule)dashboard.append(trackingSchedule);const mine=checkins.filter(c=>c.student_id===roster[0].id).slice(0,3);if(mine.length){const box=node('section',undefined,'student-coach-advice');box.append(node('h3','Consejos de mi coach'));for(const c of mine){const card=node('article');card.append(node('p',c.body),node('small',new Date(c.created_at).toLocaleString('es')));if(!c.seen_at){const seen=button('Marcar como leído',async()=>{seen.disabled=true;const {error}=await db.from('dulus_checkins').update({seen_at:new Date().toISOString()}).eq('id',c.id);if(error){seen.disabled=false;seen.textContent='Reintentar';return;}c.seen_at=new Date().toISOString();seen.textContent='Leído ✓';});card.append(seen);}box.append(card);}dashboard.append(box);}}
 const bars=node('div',undefined,'week-bars'),week=[];let scheduled=0,complete=0;
 for(let ago=6;ago>=0;ago--){const d=new Date();d.setDate(d.getDate()-ago);const date=d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');const due=plans.filter(p=>p.start_date<=date&&p.days.includes(d.getDay()));const done=due.filter(p=>sessions.some(s=>s.plan_id===p.id&&s.date===date&&s.completed_ids.length===s.total_exercises)).length;scheduled+=due.length;complete+=done;const col=node('div');col.append(node('strong',done+'/'+due.length),node('span',d.toLocaleDateString('es',{weekday:'short'})));col.style.setProperty('--bar',due.length?Math.round(done/due.length*100)+'%':'0%');col.title=date+': '+done+' de '+due.length+' entrenamientos completos';bars.append(col);week.push(done);}
 const metrics=node('div',undefined,'bridge-metrics');for(const [value,label] of [[roster.length,api.coach()?'Alumnos':'Perfil'],[sessions.length,'Sesiones registradas'],[scheduled?Math.round(complete/scheduled*100)+'%':'—','Cumplimiento · 7 días']]){const card=node('div');card.append(node('strong',String(value)),node('span',label));metrics.append(card);}dashboard.append(metrics,bars);
 const feed=node('div',undefined,'activity-feed');feed.append(node('h3',api.coach()?'Actividad del equipo':'Mi actividad'));
 const events=[];for(const s of sessions.slice(0,30)){const p=plans.find(p=>p.id===s.plan_id),student=roster.find(r=>r.id===p?.student_id),details=s.details||{};let body=(student?.name||'Alumno')+' · '+(s.completed_ids.length===s.total_exercises?'Completó ':'Registró avance en ')+(p?.name||'rutina');if(details.effort)body+=' · Esfuerzo '+details.effort+'/10';if(details.fatigue!=null)body+=' · Fatiga '+details.fatigue+'/10';if(details.pain>0)body+=' · Reportó dolor '+details.pain+'/10';
 const changes=(details.exercises||[]).filter(x=>{const target=p?.exercises.find(e=>e.exerciseId===x.exerciseId);return target&&((x.weightKg!=null&&x.weightKg!==target.weightKg)||(x.reps!=null&&x.reps!==target.reps));});if(changes.length)body+=' · Ajustó '+changes.length+' cargas/repeticiones';
 for(const x of details.exercises||[]){const earlier=sessions.filter(old=>old.date<s.date&&plans.find(q=>q.id===old.plan_id)?.student_id===p?.student_id).flatMap(old=>(old.details?.exercises||[]).filter(y=>old.completed_ids.includes(y.exerciseId)&&y.exerciseId===x.exerciseId&&y.weightKg!=null));if(s.completed_ids.includes(x.exerciseId)&&x.weightKg!=null&&earlier.length&&x.weightKg>Math.max(...earlier.map(y=>Number(y.weightKg))))body+=' · Mayor peso registrado en '+(api.catalog.find(e=>e.id===x.exerciseId)?.name||x.exerciseId);}
 events.push({time:s.updated_at||s.date,body,details:(details.exercises||[]).map(x=>(api.catalog.find(e=>e.id===x.exerciseId)?.name||x.exerciseId)+': '+(x.weightKg==null?'Peso no indicado':x.weightKg+' kg')+' · '+x.reps+' reps · RIR '+(x.rir??'—')).join('\n')});}
 for(const m of messages||[]){const p=plans.find(p=>p.id===m.plan_id);events.push({time:m.created_at,body:(roster.find(s=>s.id===p?.student_id)?.name||'Alumno')+' · '+(api.catalog.find(e=>e.id===m.exercise_id)?.name||'Ejercicio')+': '+(m.video_path?'Video para revisar':m.body),plan:p,exercise:m.exercise_id});}
 for(const e of events.sort((a,b)=>String(b.time).localeCompare(String(a.time))).slice(0,20)){const card=node('article');card.append(node('small',new Date(e.time.length===10?e.time+'T12:00:00':e.time).toLocaleString('es')),node('p',e.body));if(e.details)card.append(node('p',e.details));if(e.plan)card.append(button('Abrir ejercicio',()=>api.open(e.plan.id,e.exercise)));feed.append(card);}
 if(!events.length)feed.append(node('p','Aquí aparecerán los entrenamientos y comentarios reales del equipo.'));

 const progress=window.DulusProgress?.render({api,sessions,plans,roster,measurements,node});if(progress)dashboard.append(progress);

 dashboard.append(feed,status);status.textContent='Actividad actualizada. Los avisos se muestran con esta pantalla abierta.';
 }catch{status.textContent='No se pudo actualizar la actividad. Pulsa Actualizar para reintentar.';if(!status.isConnected)dashboard.append(status);}finally{feedBusy=false;}}
 function sync(){refreshRetention();renderDashboard();if(subUser!==api.user()){if(channel)db.removeChannel?.(channel);subUser=api.user();if(db.channel&&subUser){channel=db.channel('dulus-team-'+api.team()).on('postgres_changes',{event:'*',schema:'public',table:'dulus_sessions'},()=>renderDashboard()) .on('postgres_changes',{event:'INSERT',schema:'public',table:'dulus_messages'},()=>{renderDashboard();openMessages?.();}) .on('postgres_changes',{event:'*',schema:'public',table:'dulus_checkins'},()=>renderDashboard()).on('postgres_changes',{event:'*',schema:'public',table:'dulus_measurements'},()=>renderDashboard()).on('postgres_changes',{event:'*',schema:'public',table:'dulus_body_goals'},()=>renderDashboard()).on('postgres_changes',{event:'*',schema:'public',table:'dulus_performance_goals'},()=>renderDashboard()).on('postgres_changes',{event:'*',schema:'public',table:'dulus_performance_entries'},()=>renderDashboard()).on('postgres_changes',{event:'*',schema:'public',table:'dulus_coach_decisions'},()=>renderDashboard()).on('postgres_changes',{event:'*',schema:'public',table:'dulus_plans'},()=>api.reload?.()).subscribe();}}}
 function close(){generation++;current=null;openMessages=null;}
 return {open,exerciseView,feedbackView,snapshot,saved(){try{localStorage.removeItem(key);}catch{}},sync,close};
}};
})();
